// Catálogo CIE-10 - Clasificación Internacional de Enfermedades, 10ª Revisión
// Capítulos I al XXI — ~450 códigos representativos

const CIE10_CATALOGO = [
  // ──────────────────────────────────────────────────────────────────────────
  // Capítulo I: Enfermedades infecciosas y parasitarias (A00-B99)
  // ──────────────────────────────────────────────────────────────────────────
  { codigo: "A00", descripcion: "Cólera" },
  { codigo: "A00.0", descripcion: "Cólera debida a Vibrio cholerae O:1, biotipo clásico" },
  { codigo: "A00.1", descripcion: "Cólera debida a Vibrio cholerae O:1, biotipo El Tor" },
  { codigo: "A01", descripcion: "Fiebres tifoidea y paratifoidea" },
  { codigo: "A01.0", descripcion: "Fiebre tifoidea" },
  { codigo: "A01.1", descripcion: "Fiebre paratifoidea A" },
  { codigo: "A02", descripcion: "Otras infecciones debidas a Salmonella" },
  { codigo: "A03", descripcion: "Shigelosis" },
  { codigo: "A04.0", descripcion: "Infección intestinal debida a Escherichia coli enteropatógena" },
  { codigo: "A04.7", descripcion: "Enterocolitis debida a Clostridium difficile" },
  { codigo: "A05.0", descripcion: "Intoxicación alimentaria estafilocócica" },
  { codigo: "A06", descripcion: "Amebiasis" },
  { codigo: "A06.0", descripcion: "Disentería amebiana aguda" },
  { codigo: "A07.1", descripcion: "Giardiasis [lambliasis]" },
  { codigo: "A08.0", descripcion: "Enteritis debida a rotavirus" },
  { codigo: "A09", descripcion: "Otras gastroenteritis y colitis de origen infeccioso y no especificado" },
  { codigo: "A15", descripcion: "Tuberculosis respiratoria, confirmada bacteriológica e histológicamente" },
  { codigo: "A15.0", descripcion: "Tuberculosis del pulmón, confirmada por examen microscópico" },
  { codigo: "A16.2", descripcion: "Tuberculosis pulmonar, sin mención de confirmación bacteriológica" },
  { codigo: "A17.0", descripcion: "Meningitis tuberculosa" },
  { codigo: "A20", descripcion: "Peste" },
  { codigo: "A22", descripcion: "Carbunco [Ántrax]" },
  { codigo: "A23", descripcion: "Brucelosis" },
  { codigo: "A27", descripcion: "Leptospirosis" },
  { codigo: "A30", descripcion: "Lepra [Enfermedad de Hansen]" },
  { codigo: "A33", descripcion: "Tétanos neonatal" },
  { codigo: "A34", descripcion: "Tétanos obstétrico" },
  { codigo: "A35", descripcion: "Otros tipos de tétanos" },
  { codigo: "A36", descripcion: "Difteria" },
  { codigo: "A37", descripcion: "Tos ferina [Pertussis]" },
  { codigo: "A38", descripcion: "Escarlatina" },
  { codigo: "A39", descripcion: "Infección meningocócica" },
  { codigo: "A40", descripcion: "Septicemia estreptocócica" },
  { codigo: "A41", descripcion: "Otras septicemias" },
  { codigo: "A41.0", descripcion: "Septicemia debida a Staphylococcus aureus" },
  { codigo: "A41.5", descripcion: "Septicemia debida a otros microorganismos gramnegativos" },
  { codigo: "A41.9", descripcion: "Septicemia, no especificada" },
  { codigo: "A46", descripcion: "Erisipela" },
  { codigo: "A49.0", descripcion: "Infección estafilocócica de sitio no especificado" },
  { codigo: "A50", descripcion: "Sífilis congénita" },
  { codigo: "A51", descripcion: "Sífilis temprana" },
  { codigo: "A52", descripcion: "Sífilis tardía" },
  { codigo: "A53.9", descripcion: "Sífilis, no especificada" },
  { codigo: "A54", descripcion: "Infección gonocócica" },
  { codigo: "A55", descripcion: "Linfogranuloma (venéreo) por clamidias" },
  { codigo: "A56", descripcion: "Otras enfermedades de transmisión sexual debidas a clamidias" },
  { codigo: "A59", descripcion: "Tricomoniasis" },
  { codigo: "A60", descripcion: "Infección anogenital debida a virus herpes simplex" },
  { codigo: "A63.0", descripcion: "Condiloma acuminado" },
  { codigo: "A69.2", descripcion: "Enfermedad de Lyme" },
  { codigo: "A80", descripcion: "Poliomielitis aguda" },
  { codigo: "A82", descripcion: "Rabia" },
  { codigo: "A83", descripcion: "Encefalitis viral transmitida por mosquitos" },
  { codigo: "A84", descripcion: "Encefalitis viral transmitida por garrapatas" },
  { codigo: "A87", descripcion: "Meningitis viral" },
  { codigo: "A90", descripcion: "Fiebre del dengue [dengue clásico]" },
  { codigo: "A91", descripcion: "Fiebre del dengue hemorrágico" },
  { codigo: "A92.0", descripcion: "Enfermedad por virus Chikungunya" },
  { codigo: "A95", descripcion: "Fiebre amarilla" },
  { codigo: "A98.5", descripcion: "Enfermedad por virus Zika" },
  { codigo: "B00", descripcion: "Infecciones debidas a virus herpes simplex [herpes simple]" },
  { codigo: "B01", descripcion: "Varicela" },
  { codigo: "B02", descripcion: "Herpes zóster" },
  { codigo: "B05", descripcion: "Sarampión" },
  { codigo: "B06", descripcion: "Rubéola [sarampión alemán]" },
  { codigo: "B07", descripcion: "Verrugas víricas" },
  { codigo: "B08.5", descripcion: "Faringitis vesicular con exantema por enterovirus" },
  { codigo: "B10", descripcion: "Otras infecciones por herpesvirus humanos" },
  { codigo: "B15", descripcion: "Hepatitis aguda tipo A" },
  { codigo: "B16", descripcion: "Hepatitis aguda tipo B" },
  { codigo: "B17.1", descripcion: "Hepatitis aguda tipo C" },
  { codigo: "B18", descripcion: "Hepatitis viral crónica" },
  { codigo: "B18.1", descripcion: "Hepatitis B crónica sin agente delta" },
  { codigo: "B18.2", descripcion: "Hepatitis C crónica" },
  { codigo: "B20", descripcion: "Enfermedad por VIH, resultante en enfermedades infecciosas y parasitarias" },
  { codigo: "B23.0", descripcion: "Síndrome de infección aguda debida a VIH" },
  { codigo: "B24", descripcion: "Enfermedad por VIH, no especificada" },
  { codigo: "B25", descripcion: "Enfermedad debida a citomegalovirus" },
  { codigo: "B26", descripcion: "Parotiditis infecciosa [paperas]" },
  { codigo: "B34.9", descripcion: "Infección viral de sitio no especificado" },
  { codigo: "B35", descripcion: "Dermatofitosis" },
  { codigo: "B36.0", descripcion: "Pitiriasis versicolor" },
  { codigo: "B37", descripcion: "Candidiasis" },
  { codigo: "B37.0", descripcion: "Estomatitis candidiásica" },
  { codigo: "B37.3", descripcion: "Candidiasis de la vulva y de la vagina" },
  { codigo: "B45", descripcion: "Criptococosis" },
  { codigo: "B50", descripcion: "Paludismo debido a Plasmodium falciparum" },
  { codigo: "B54", descripcion: "Paludismo no especificado" },
  { codigo: "B65", descripcion: "Esquistosomiasis [bilharziasis]" },
  { codigo: "B74", descripcion: "Filariasis" },
  { codigo: "B76", descripcion: "Anquilostomiasis" },
  { codigo: "B77", descripcion: "Ascariasis" },
  { codigo: "B80", descripcion: "Oxiuriasis" },
  { codigo: "B82", descripcion: "Parasitosis intestinal, no especificada" },
  { codigo: "B86", descripcion: "Escabiosis [sarna]" },

  // ──────────────────────────────────────────────────────────────────────────
  // Capítulo II: Neoplasias (C00-D48)
  // ──────────────────────────────────────────────────────────────────────────
  { codigo: "C00", descripcion: "Tumor maligno del labio" },
  { codigo: "C01", descripcion: "Tumor maligno de la base de la lengua" },
  { codigo: "C02", descripcion: "Tumor maligno de otras partes y las no especificadas de la lengua" },
  { codigo: "C03", descripcion: "Tumor maligno de la encía" },
  { codigo: "C04", descripcion: "Tumor maligno del piso de la boca" },
  { codigo: "C07", descripcion: "Tumor maligno de la glándula parótida" },
  { codigo: "C15", descripcion: "Tumor maligno del esófago" },
  { codigo: "C16", descripcion: "Tumor maligno del estómago" },
  { codigo: "C16.9", descripcion: "Tumor maligno del estómago, parte no especificada" },
  { codigo: "C18", descripcion: "Tumor maligno del colon" },
  { codigo: "C18.9", descripcion: "Tumor maligno del colon, parte no especificada" },
  { codigo: "C19", descripcion: "Tumor maligno de la unión rectosigmoide" },
  { codigo: "C20", descripcion: "Tumor maligno del recto" },
  { codigo: "C22", descripcion: "Tumor maligno del hígado y de los conductos biliares intrahepáticos" },
  { codigo: "C22.0", descripcion: "Carcinoma de células hepáticas" },
  { codigo: "C23", descripcion: "Tumor maligno de la vesícula biliar" },
  { codigo: "C25", descripcion: "Tumor maligno del páncreas" },
  { codigo: "C25.0", descripcion: "Tumor maligno de la cabeza del páncreas" },
  { codigo: "C32", descripcion: "Tumor maligno de la laringe" },
  { codigo: "C33", descripcion: "Tumor maligno de la tráquea" },
  { codigo: "C34", descripcion: "Tumor maligno de los bronquios y del pulmón" },
  { codigo: "C34.1", descripcion: "Tumor maligno del lóbulo superior del bronquio o del pulmón" },
  { codigo: "C34.9", descripcion: "Tumor maligno de los bronquios y del pulmón, no especificado" },
  { codigo: "C43", descripcion: "Melanoma maligno de la piel" },
  { codigo: "C44", descripcion: "Otros tumores malignos de la piel" },
  { codigo: "C50", descripcion: "Tumor maligno de la mama" },
  { codigo: "C50.9", descripcion: "Tumor maligno de la mama, parte no especificada" },
  { codigo: "C53", descripcion: "Tumor maligno del cuello del útero" },
  { codigo: "C53.9", descripcion: "Tumor maligno del cuello del útero, sin otra especificación" },
  { codigo: "C54", descripcion: "Tumor maligno del cuerpo del útero" },
  { codigo: "C56", descripcion: "Tumor maligno del ovario" },
  { codigo: "C61", descripcion: "Tumor maligno de la próstata" },
  { codigo: "C62", descripcion: "Tumor maligno del testículo" },
  { codigo: "C64", descripcion: "Tumor maligno del riñón, excepto de la pelvis renal" },
  { codigo: "C67", descripcion: "Tumor maligno de la vejiga urinaria" },
  { codigo: "C70", descripcion: "Tumor maligno de las meninges" },
  { codigo: "C71", descripcion: "Tumor maligno del encéfalo" },
  { codigo: "C71.9", descripcion: "Tumor maligno del encéfalo, parte no especificada" },
  { codigo: "C73", descripcion: "Tumor maligno de la glándula tiroides" },
  { codigo: "C77", descripcion: "Tumor maligno secundario y no especificado de los ganglios linfáticos" },
  { codigo: "C79", descripcion: "Tumor maligno secundario de otros sitios y de los no especificados" },
  { codigo: "C80", descripcion: "Tumor maligno, sin especificación de sitio" },
  { codigo: "C81", descripcion: "Enfermedad de Hodgkin" },
  { codigo: "C82", descripcion: "Linfoma no Hodgkin folicular [nodular]" },
  { codigo: "C83", descripcion: "Linfoma no Hodgkin difuso" },
  { codigo: "C90", descripcion: "Mieloma múltiple y tumores malignos de células plasmáticas" },
  { codigo: "C91", descripcion: "Leucemia linfoide" },
  { codigo: "C91.0", descripcion: "Leucemia linfoblástica aguda" },
  { codigo: "C92", descripcion: "Leucemia mieloide" },
  { codigo: "C92.0", descripcion: "Leucemia mieloide aguda" },
  { codigo: "C92.1", descripcion: "Leucemia mieloide crónica" },
  { codigo: "D10", descripcion: "Tumor benigno de la boca y de la faringe" },
  { codigo: "D12", descripcion: "Tumor benigno del colon, del recto, del conducto anal y del ano" },
  { codigo: "D21", descripcion: "Otros tumores benignos del tejido conjuntivo y de otros tejidos blandos" },
  { codigo: "D25", descripcion: "Leiomioma del útero" },
  { codigo: "D27", descripcion: "Tumor benigno del ovario" },
  { codigo: "D35.0", descripcion: "Tumor benigno de la glándula suprarrenal" },
  { codigo: "D44", descripcion: "Tumor de comportamiento incierto de las glándulas endocrinas" },

  // ──────────────────────────────────────────────────────────────────────────
  // Capítulo III: Enfermedades de la sangre (D50-D89)
  // ──────────────────────────────────────────────────────────────────────────
  { codigo: "D50", descripcion: "Anemias por deficiencia de hierro" },
  { codigo: "D50.0", descripcion: "Anemia por deficiencia de hierro secundaria a pérdida de sangre" },
  { codigo: "D50.9", descripcion: "Anemia por deficiencia de hierro, no especificada" },
  { codigo: "D51", descripcion: "Anemia por deficiencia de vitamina B12" },
  { codigo: "D52", descripcion: "Anemia por deficiencia de folato" },
  { codigo: "D53.9", descripcion: "Anemia por deficiencia nutritiva, no especificada" },
  { codigo: "D55", descripcion: "Anemia debida a trastornos enzimáticos" },
  { codigo: "D56", descripcion: "Talasemia" },
  { codigo: "D57", descripcion: "Trastornos falciformes" },
  { codigo: "D58", descripcion: "Otras anemias hemolíticas hereditarias" },
  { codigo: "D59", descripcion: "Anemia hemolítica adquirida" },
  { codigo: "D60", descripcion: "Aplasia eritrocítica adquirida [eritroblastopenia]" },
  { codigo: "D61", descripcion: "Otras anemias aplásticas" },
  { codigo: "D64", descripcion: "Otras anemias" },
  { codigo: "D64.9", descripcion: "Anemia, no especificada" },
  { codigo: "D65", descripcion: "Coagulación intravascular diseminada [síndrome de desfibrinación]" },
  { codigo: "D66", descripcion: "Deficiencia hereditaria del factor VIII" },
  { codigo: "D68", descripcion: "Otros defectos de la coagulación" },
  { codigo: "D69", descripcion: "Púrpura y otras afecciones hemorrágicas" },
  { codigo: "D70", descripcion: "Agranulocitosis" },
  { codigo: "D72", descripcion: "Otros trastornos de los leucocitos" },
  { codigo: "D73", descripcion: "Enfermedades del bazo" },
  { codigo: "D80", descripcion: "Inmunodeficiencia con predominio de defectos de anticuerpos" },
  { codigo: "D83", descripcion: "Inmunodeficiencia variable común" },
  { codigo: "D86", descripcion: "Sarcoidosis" },

  // ──────────────────────────────────────────────────────────────────────────
  // Capítulo IV: Enfermedades endocrinas, nutricionales y metabólicas (E00-E90)
  // ──────────────────────────────────────────────────────────────────────────
  { codigo: "E00", descripcion: "Síndrome congénito de deficiencia de yodo" },
  { codigo: "E01", descripcion: "Trastornos tiroideos vinculados a deficiencia de yodo y afecciones similares" },
  { codigo: "E03", descripcion: "Otro hipotiroidismo" },
  { codigo: "E03.9", descripcion: "Hipotiroidismo, no especificado" },
  { codigo: "E04", descripcion: "Otro bocio no tóxico" },
  { codigo: "E05", descripcion: "Tirotoxicosis [hipertiroidismo]" },
  { codigo: "E05.0", descripcion: "Tirotoxicosis con bocio difuso" },
  { codigo: "E06", descripcion: "Tiroiditis" },
  { codigo: "E07", descripcion: "Otros trastornos de la tiroides" },
  { codigo: "E10", descripcion: "Diabetes mellitus tipo 1" },
  { codigo: "E10.0", descripcion: "Diabetes mellitus tipo 1 con coma" },
  { codigo: "E10.5", descripcion: "Diabetes mellitus tipo 1 con complicaciones circulatorias periféricas" },
  { codigo: "E10.9", descripcion: "Diabetes mellitus tipo 1 sin complicaciones" },
  { codigo: "E11", descripcion: "Diabetes mellitus tipo 2" },
  { codigo: "E11.0", descripcion: "Diabetes mellitus tipo 2 con coma" },
  { codigo: "E11.2", descripcion: "Diabetes mellitus tipo 2 con complicaciones renales" },
  { codigo: "E11.3", descripcion: "Diabetes mellitus tipo 2 con complicaciones oftálmicas" },
  { codigo: "E11.5", descripcion: "Diabetes mellitus tipo 2 con complicaciones circulatorias periféricas" },
  { codigo: "E11.6", descripcion: "Diabetes mellitus tipo 2 con otras complicaciones especificadas" },
  { codigo: "E11.9", descripcion: "Diabetes mellitus tipo 2 sin complicaciones" },
  { codigo: "E14", descripcion: "Diabetes mellitus, no especificada" },
  { codigo: "E16.0", descripcion: "Hipoglucemia sin coma, inducida por drogas" },
  { codigo: "E16.2", descripcion: "Hipoglucemia, no especificada" },
  { codigo: "E20", descripcion: "Hipoparatiroidismo" },
  { codigo: "E21", descripcion: "Hiperparatiroidismo y otros trastornos de la glándula paratiroides" },
  { codigo: "E22.0", descripcion: "Acromegalia y gigantismo hipofisario" },
  { codigo: "E22.1", descripcion: "Hiperprolactinemia" },
  { codigo: "E23.0", descripcion: "Hipopituitarismo" },
  { codigo: "E24", descripcion: "Síndrome de Cushing" },
  { codigo: "E25", descripcion: "Trastornos adrenogenitales" },
  { codigo: "E27.1", descripcion: "Insuficiencia corticosuprarrenal primaria" },
  { codigo: "E27.4", descripcion: "Otras insuficiencias corticosuprarrenales y las no especificadas" },
  { codigo: "E28", descripcion: "Disfunción ovárica" },
  { codigo: "E29", descripcion: "Disfunción testicular" },
  { codigo: "E34.0", descripcion: "Síndrome carcinoide" },
  { codigo: "E40", descripcion: "Kwashiorkor" },
  { codigo: "E41", descripcion: "Marasmo nutricional" },
  { codigo: "E43", descripcion: "Desnutrición proteicocalórica grave, no especificada" },
  { codigo: "E44", descripcion: "Desnutrición proteicocalórica de grado moderado y leve" },
  { codigo: "E46", descripcion: "Desnutrición proteicocalórica, no especificada" },
  { codigo: "E50", descripcion: "Deficiencia de vitamina A" },
  { codigo: "E55", descripcion: "Deficiencia de vitamina D" },
  { codigo: "E55.9", descripcion: "Deficiencia de vitamina D, no especificada" },
  { codigo: "E61.1", descripcion: "Deficiencia de hierro" },
  { codigo: "E63.9", descripcion: "Deficiencia nutricional, no especificada" },
  { codigo: "E65", descripcion: "Adiposidad localizada" },
  { codigo: "E66", descripcion: "Obesidad" },
  { codigo: "E66.0", descripcion: "Obesidad debida a exceso de calorías" },
  { codigo: "E66.9", descripcion: "Obesidad, no especificada" },
  { codigo: "E70", descripcion: "Trastornos del metabolismo de aminoácidos aromáticos" },
  { codigo: "E72", descripcion: "Otros trastornos del metabolismo de los aminoácidos" },
  { codigo: "E78", descripcion: "Trastornos del metabolismo de las lipoproteínas y otras lipidemias" },
  { codigo: "E78.0", descripcion: "Hipercolesterolemia pura" },
  { codigo: "E78.1", descripcion: "Hipertrigliceridemia pura" },
  { codigo: "E78.2", descripcion: "Hiperlipidemia mixta" },
  { codigo: "E78.5", descripcion: "Hiperlipidemia, no especificada" },
  { codigo: "E83.1", descripcion: "Trastornos del metabolismo del hierro" },
  { codigo: "E87.0", descripcion: "Hiperosmolaridad e hipernatremia" },
  { codigo: "E87.1", descripcion: "Hiposmolaridad e hiponatremia" },
  { codigo: "E87.2", descripcion: "Acidosis" },
  { codigo: "E87.3", descripcion: "Alcalosis" },
  { codigo: "E87.5", descripcion: "Hiperpotasemia" },
  { codigo: "E87.6", descripcion: "Hipopotasemia" },
  { codigo: "E88.0", descripcion: "Trastornos del metabolismo de las proteínas del plasma" },

  // ──────────────────────────────────────────────────────────────────────────
  // Capítulo V: Trastornos mentales y del comportamiento (F00-F99)
  // ──────────────────────────────────────────────────────────────────────────
  { codigo: "F00", descripcion: "Demencia en la enfermedad de Alzheimer" },
  { codigo: "F01", descripcion: "Demencia vascular" },
  { codigo: "F03", descripcion: "Demencia, no especificada" },
  { codigo: "F05", descripcion: "Delirium, no inducido por alcohol u otras sustancias psicoactivas" },
  { codigo: "F06", descripcion: "Otros trastornos mentales debidos a lesión o disfunción cerebral" },
  { codigo: "F10", descripcion: "Trastornos mentales y del comportamiento debidos al uso del alcohol" },
  { codigo: "F10.1", descripcion: "Trastornos por uso perjudicial de alcohol" },
  { codigo: "F10.2", descripcion: "Síndrome de dependencia al alcohol" },
  { codigo: "F11", descripcion: "Trastornos mentales y del comportamiento debidos al uso de opiáceos" },
  { codigo: "F12", descripcion: "Trastornos mentales debidos al uso de cannabinoides" },
  { codigo: "F14", descripcion: "Trastornos mentales debidos al uso de cocaína" },
  { codigo: "F19", descripcion: "Trastornos mentales debidos al uso de múltiples drogas" },
  { codigo: "F20", descripcion: "Esquizofrenia" },
  { codigo: "F20.0", descripcion: "Esquizofrenia paranoide" },
  { codigo: "F20.1", descripcion: "Esquizofrenia hebefrénica" },
  { codigo: "F20.3", descripcion: "Esquizofrenia indiferenciada" },
  { codigo: "F20.9", descripcion: "Esquizofrenia, no especificada" },
  { codigo: "F25", descripcion: "Trastornos esquizoafectivos" },
  { codigo: "F30", descripcion: "Episodio maníaco" },
  { codigo: "F31", descripcion: "Trastorno afectivo bipolar" },
  { codigo: "F31.9", descripcion: "Trastorno afectivo bipolar, no especificado" },
  { codigo: "F32", descripcion: "Episodios depresivos" },
  { codigo: "F32.0", descripcion: "Episodio depresivo leve" },
  { codigo: "F32.1", descripcion: "Episodio depresivo moderado" },
  { codigo: "F32.2", descripcion: "Episodio depresivo grave sin síntomas psicóticos" },
  { codigo: "F32.3", descripcion: "Episodio depresivo grave con síntomas psicóticos" },
  { codigo: "F32.9", descripcion: "Episodio depresivo, no especificado" },
  { codigo: "F33", descripcion: "Trastorno depresivo recurrente" },
  { codigo: "F40", descripcion: "Trastornos fóbico-ansiosos" },
  { codigo: "F41", descripcion: "Otros trastornos de ansiedad" },
  { codigo: "F41.0", descripcion: "Trastorno de pánico [ansiedad paroxística episódica]" },
  { codigo: "F41.1", descripcion: "Trastorno de ansiedad generalizada" },
  { codigo: "F41.9", descripcion: "Trastorno de ansiedad, no especificado" },
  { codigo: "F42", descripcion: "Trastorno obsesivo-compulsivo" },
  { codigo: "F43", descripcion: "Reacciones al estrés grave y trastornos de adaptación" },
  { codigo: "F43.1", descripcion: "Trastorno por estrés postraumático" },
  { codigo: "F44", descripcion: "Trastornos disociativos [de conversión]" },
  { codigo: "F45", descripcion: "Trastornos somatomorfos" },
  { codigo: "F50", descripcion: "Trastornos de la ingestión de alimentos" },
  { codigo: "F50.0", descripcion: "Anorexia nerviosa" },
  { codigo: "F50.2", descripcion: "Bulimia nerviosa" },
  { codigo: "F51", descripcion: "Trastornos no orgánicos del sueño" },
  { codigo: "F60", descripcion: "Trastornos de la personalidad específicos" },
  { codigo: "F70", descripcion: "Retraso mental leve" },
  { codigo: "F80", descripcion: "Trastornos específicos del desarrollo del habla y del lenguaje" },
  { codigo: "F84.0", descripcion: "Autismo en la niñez" },
  { codigo: "F90", descripcion: "Trastornos hipercinéticos" },
  { codigo: "F90.0", descripcion: "Perturbación de la actividad y de la atención (TDAH)" },
  { codigo: "F91", descripcion: "Trastornos de la conducta" },
  { codigo: "F98.0", descripcion: "Enuresis no orgánica" },

  // ──────────────────────────────────────────────────────────────────────────
  // Capítulo VI: Enfermedades del sistema nervioso (G00-G99)
  // ──────────────────────────────────────────────────────────────────────────
  { codigo: "G00", descripcion: "Meningitis bacteriana, no clasificada en otra parte" },
  { codigo: "G00.9", descripcion: "Meningitis bacteriana, no especificada" },
  { codigo: "G03", descripcion: "Meningitis debida a otras causas y a causas no especificadas" },
  { codigo: "G04", descripcion: "Encefalitis, mielitis y encefalomielitis" },
  { codigo: "G06", descripcion: "Absceso y granuloma intracraneal e intrarraquídeo" },
  { codigo: "G10", descripcion: "Enfermedad de Huntington" },
  { codigo: "G20", descripcion: "Enfermedad de Parkinson" },
  { codigo: "G21", descripcion: "Parkinsonismo secundario" },
  { codigo: "G25.0", descripcion: "Temblor esencial" },
  { codigo: "G30", descripcion: "Enfermedad de Alzheimer" },
  { codigo: "G30.9", descripcion: "Enfermedad de Alzheimer, no especificada" },
  { codigo: "G35", descripcion: "Esclerosis múltiple" },
  { codigo: "G40", descripcion: "Epilepsia" },
  { codigo: "G40.0", descripcion: "Epilepsia y síndromes epilépticos idiopáticos definidos por su localización" },
  { codigo: "G40.3", descripcion: "Epilepsia generalizada idiopática" },
  { codigo: "G40.9", descripcion: "Epilepsia, tipo no especificado" },
  { codigo: "G41", descripcion: "Estado epiléptico" },
  { codigo: "G43", descripcion: "Migraña" },
  { codigo: "G43.0", descripcion: "Migraña sin aura [migraña común]" },
  { codigo: "G43.1", descripcion: "Migraña con aura [migraña clásica]" },
  { codigo: "G43.9", descripcion: "Migraña, no especificada" },
  { codigo: "G44", descripcion: "Otros síndromes de cefalea" },
  { codigo: "G45", descripcion: "Ataques de isquemia cerebral transitoria y síndromes afines" },
  { codigo: "G45.9", descripcion: "Ataque isquémico transitorio, no especificado" },
  { codigo: "G47", descripcion: "Trastornos del sueño" },
  { codigo: "G47.3", descripcion: "Apnea del sueño" },
  { codigo: "G51", descripcion: "Trastornos del nervio facial" },
  { codigo: "G51.0", descripcion: "Parálisis de Bell" },
  { codigo: "G54", descripcion: "Trastornos de las raíces y plexos nerviosos" },
  { codigo: "G56", descripcion: "Mononeuropatías del miembro superior" },
  { codigo: "G56.0", descripcion: "Síndrome del túnel carpiano" },
  { codigo: "G60", descripcion: "Neuropatía hereditaria e idiopática" },
  { codigo: "G61.0", descripcion: "Síndrome de Guillain-Barré" },
  { codigo: "G62.9", descripcion: "Polineuropatía, no especificada" },
  { codigo: "G63", descripcion: "Polineuropatía en enfermedades clasificadas en otra parte" },
  { codigo: "G70", descripcion: "Miastenia gravis y otros trastornos neuromusculares" },
  { codigo: "G71", descripcion: "Trastornos musculares primarios" },
  { codigo: "G80", descripcion: "Parálisis cerebral" },
  { codigo: "G81", descripcion: "Hemiplejía" },
  { codigo: "G82", descripcion: "Paraplejía y cuadriplejía" },
  { codigo: "G89.0", descripcion: "Dolor central" },
  { codigo: "G89.2", descripcion: "Dolor crónico, no clasificado en otra parte" },
  { codigo: "G91", descripcion: "Hidrocefalia" },
  { codigo: "G93.1", descripcion: "Encefalopatía anóxica, no clasificada en otra parte" },
  { codigo: "G93.4", descripcion: "Encefalopatía, no especificada" },

  // ──────────────────────────────────────────────────────────────────────────
  // Capítulo VII: Enfermedades del ojo y sus anexos (H00-H59)
  // ──────────────────────────────────────────────────────────────────────────
  { codigo: "H00", descripcion: "Orzuelo y calacio" },
  { codigo: "H01", descripcion: "Otras inflamaciones del párpado" },
  { codigo: "H10", descripcion: "Conjuntivitis" },
  { codigo: "H10.1", descripcion: "Conjuntivitis aguda atópica" },
  { codigo: "H10.9", descripcion: "Conjuntivitis, no especificada" },
  { codigo: "H11.3", descripcion: "Hemorragia conjuntival" },
  { codigo: "H16", descripcion: "Queratitis" },
  { codigo: "H20", descripcion: "Iridociclitis" },
  { codigo: "H25", descripcion: "Catarata senil" },
  { codigo: "H26", descripcion: "Otras cataratas" },
  { codigo: "H30", descripcion: "Inflamación coriorretiniana" },
  { codigo: "H33", descripcion: "Desprendimiento y desgarro de la retina" },
  { codigo: "H35", descripcion: "Otros trastornos de la retina" },
  { codigo: "H35.3", descripcion: "Degeneración de la mácula y del polo posterior del ojo" },
  { codigo: "H36.0", descripcion: "Retinopatía diabética" },
  { codigo: "H40", descripcion: "Glaucoma" },
  { codigo: "H40.1", descripcion: "Glaucoma primario de ángulo abierto" },
  { codigo: "H40.2", descripcion: "Glaucoma primario de ángulo cerrado" },
  { codigo: "H43", descripcion: "Trastornos del humor vítreo" },
  { codigo: "H44", descripcion: "Trastornos del globo ocular" },
  { codigo: "H52", descripcion: "Trastornos de la acomodación y de la refracción" },
  { codigo: "H52.0", descripcion: "Hipermetropía" },
  { codigo: "H52.1", descripcion: "Miopía" },
  { codigo: "H52.2", descripcion: "Astigmatismo" },
  { codigo: "H52.4", descripcion: "Presbicia" },
  { codigo: "H53.0", descripcion: "Ambliopía por anopsia" },
  { codigo: "H54", descripcion: "Ceguera y visión reducida" },

  // ──────────────────────────────────────────────────────────────────────────
  // Capítulo VIII: Enfermedades del oído (H60-H95)
  // ──────────────────────────────────────────────────────────────────────────
  { codigo: "H60", descripcion: "Otitis externa" },
  { codigo: "H65", descripcion: "Otitis media no supurativa" },
  { codigo: "H65.0", descripcion: "Otitis media aguda serosa" },
  { codigo: "H66", descripcion: "Otitis media supurativa y las no especificadas" },
  { codigo: "H66.0", descripcion: "Otitis media supurativa aguda" },
  { codigo: "H66.3", descripcion: "Otitis media crónica supurativa, no especificada" },
  { codigo: "H71", descripcion: "Colesteatoma del oído medio" },
  { codigo: "H72", descripcion: "Perforación de la membrana timpánica" },
  { codigo: "H80", descripcion: "Otosclerosis" },
  { codigo: "H81", descripcion: "Trastornos de la función vestibular" },
  { codigo: "H81.0", descripcion: "Enfermedad de Ménière" },
  { codigo: "H81.3", descripcion: "Otros vértigos periféricos" },
  { codigo: "H83.3", descripcion: "Ruido en el oído [tinnitus]" },
  { codigo: "H90", descripcion: "Hipoacusia conductiva y neurosensorial" },
  { codigo: "H91", descripcion: "Otras pérdidas de la audición" },
  { codigo: "H91.9", descripcion: "Pérdida de la audición, no especificada" },

  // ──────────────────────────────────────────────────────────────────────────
  // Capítulo IX: Enfermedades del sistema circulatorio (I00-I99)
  // ──────────────────────────────────────────────────────────────────────────
  { codigo: "I00", descripcion: "Fiebre reumática sin mención de complicación cardíaca" },
  { codigo: "I05", descripcion: "Enfermedades reumáticas de la válvula mitral" },
  { codigo: "I06", descripcion: "Enfermedades reumáticas de la válvula aórtica" },
  { codigo: "I09.9", descripcion: "Enfermedad cardíaca reumática, no especificada" },
  { codigo: "I10", descripcion: "Hipertensión esencial (primaria)" },
  { codigo: "I11", descripcion: "Enfermedad cardíaca hipertensiva" },
  { codigo: "I12", descripcion: "Enfermedad renal hipertensiva" },
  { codigo: "I13", descripcion: "Enfermedad cardiorrenal hipertensiva" },
  { codigo: "I15", descripcion: "Hipertensión secundaria" },
  { codigo: "I20", descripcion: "Angina de pecho" },
  { codigo: "I20.0", descripcion: "Angina inestable" },
  { codigo: "I20.9", descripcion: "Angina de pecho, no especificada" },
  { codigo: "I21", descripcion: "Infarto agudo de miocardio" },
  { codigo: "I21.0", descripcion: "Infarto agudo de miocardio de la pared anterior" },
  { codigo: "I21.1", descripcion: "Infarto agudo de miocardio de la pared inferior" },
  { codigo: "I21.9", descripcion: "Infarto agudo de miocardio, sin otra especificación" },
  { codigo: "I22", descripcion: "Infarto subsiguiente de miocardio" },
  { codigo: "I24.0", descripcion: "Trombosis coronaria que no resulta en infarto de miocardio" },
  { codigo: "I25", descripcion: "Enfermedad isquémica crónica del corazón" },
  { codigo: "I25.1", descripcion: "Enfermedad aterosclerótica del corazón" },
  { codigo: "I26", descripcion: "Embolia pulmonar" },
  { codigo: "I27.0", descripcion: "Hipertensión pulmonar primaria" },
  { codigo: "I30", descripcion: "Pericarditis aguda" },
  { codigo: "I33", descripcion: "Endocarditis aguda y subaguda" },
  { codigo: "I34", descripcion: "Trastornos no reumáticos de la válvula mitral" },
  { codigo: "I35", descripcion: "Trastornos no reumáticos de la válvula aórtica" },
  { codigo: "I42", descripcion: "Cardiomiopatía" },
  { codigo: "I42.0", descripcion: "Cardiomiopatía dilatada" },
  { codigo: "I44", descripcion: "Bloqueo auriculoventricular y de rama izquierda" },
  { codigo: "I45", descripcion: "Otros trastornos de la conducción cardíaca" },
  { codigo: "I47", descripcion: "Taquicardia paroxística" },
  { codigo: "I47.1", descripcion: "Taquicardia supraventricular" },
  { codigo: "I48", descripcion: "Fibrilación y aleteo auricular" },
  { codigo: "I48.0", descripcion: "Fibrilación auricular paroxística" },
  { codigo: "I48.9", descripcion: "Fibrilación y aleteo auricular, no especificados" },
  { codigo: "I49", descripcion: "Otras arritmias cardíacas" },
  { codigo: "I50", descripcion: "Insuficiencia cardíaca" },
  { codigo: "I50.0", descripcion: "Insuficiencia cardíaca congestiva" },
  { codigo: "I50.1", descripcion: "Insuficiencia ventricular izquierda" },
  { codigo: "I50.9", descripcion: "Insuficiencia cardíaca, no especificada" },
  { codigo: "I60", descripcion: "Hemorragia subaracnoidea" },
  { codigo: "I61", descripcion: "Hemorragia intracerebral" },
  { codigo: "I63", descripcion: "Infarto cerebral" },
  { codigo: "I63.9", descripcion: "Infarto cerebral, no especificado" },
  { codigo: "I64", descripcion: "Accidente vascular encefálico, no especificado como hemorrágico o isquémico" },
  { codigo: "I65", descripcion: "Oclusión y estenosis de las arterias precerebrales" },
  { codigo: "I69", descripcion: "Secuelas de enfermedades cerebrovasculares" },
  { codigo: "I70", descripcion: "Aterosclerosis" },
  { codigo: "I71", descripcion: "Aneurisma y disección aórticos" },
  { codigo: "I71.4", descripcion: "Aneurisma abdominal de la aorta, sin mención de ruptura" },
  { codigo: "I73.0", descripcion: "Síndrome de Raynaud" },
  { codigo: "I74", descripcion: "Embolia y trombosis arteriales" },
  { codigo: "I80", descripcion: "Flebitis y tromboflebitis" },
  { codigo: "I82", descripcion: "Otra embolia y trombosis venosas" },
  { codigo: "I83", descripcion: "Várices de los miembros inferiores" },
  { codigo: "I84", descripcion: "Hemorroides" },
  { codigo: "I87.0", descripcion: "Síndrome postflebítico" },
  { codigo: "I89.0", descripcion: "Linfedema, no clasificado en otra parte" },
  { codigo: "I95.1", descripcion: "Hipotensión ortostática" },

  // ──────────────────────────────────────────────────────────────────────────
  // Capítulo X: Enfermedades del sistema respiratorio (J00-J99)
  // ──────────────────────────────────────────────────────────────────────────
  { codigo: "J00", descripcion: "Rinofaringitis aguda [resfriado común]" },
  { codigo: "J01", descripcion: "Sinusitis aguda" },
  { codigo: "J01.9", descripcion: "Sinusitis aguda, no especificada" },
  { codigo: "J02", descripcion: "Faringitis aguda" },
  { codigo: "J02.0", descripcion: "Faringitis estreptocócica" },
  { codigo: "J02.9", descripcion: "Faringitis aguda, no especificada" },
  { codigo: "J03", descripcion: "Amigdalitis aguda" },
  { codigo: "J04", descripcion: "Laringitis y traqueítis agudas" },
  { codigo: "J06", descripcion: "Infecciones agudas de las vías respiratorias superiores, de sitios múltiples o no especificados" },
  { codigo: "J06.9", descripcion: "Infección aguda de las vías respiratorias superiores, no especificada" },
  { codigo: "J09", descripcion: "Influenza debida a virus de la influenza identificado" },
  { codigo: "J10", descripcion: "Influenza debida a otro virus de la influenza identificado" },
  { codigo: "J11", descripcion: "Influenza debida a virus no identificado" },
  { codigo: "J11.1", descripcion: "Influenza con otras manifestaciones respiratorias, virus no identificado" },
  { codigo: "J12", descripcion: "Neumonía viral, no clasificada en otra parte" },
  { codigo: "J13", descripcion: "Neumonía debida a Streptococcus pneumoniae" },
  { codigo: "J14", descripcion: "Neumonía debida a Haemophilus influenzae" },
  { codigo: "J15", descripcion: "Neumonía bacteriana, no clasificada en otra parte" },
  { codigo: "J15.0", descripcion: "Neumonía debida a Klebsiella pneumoniae" },
  { codigo: "J15.2", descripcion: "Neumonía debida a Staphylococcus" },
  { codigo: "J15.9", descripcion: "Neumonía bacteriana, no especificada" },
  { codigo: "J18", descripcion: "Neumonía, microorganismo no especificado" },
  { codigo: "J18.9", descripcion: "Neumonía, no especificada" },
  { codigo: "J20", descripcion: "Bronquitis aguda" },
  { codigo: "J20.9", descripcion: "Bronquitis aguda, no especificada" },
  { codigo: "J22", descripcion: "Infección aguda de las vías respiratorias inferiores, no especificada" },
  { codigo: "J30", descripcion: "Rinitis alérgica y vasomotora" },
  { codigo: "J30.0", descripcion: "Rinitis vasomotora" },
  { codigo: "J30.1", descripcion: "Rinitis alérgica debida al polen" },
  { codigo: "J30.4", descripcion: "Rinitis alérgica, no especificada" },
  { codigo: "J32", descripcion: "Sinusitis crónica" },
  { codigo: "J35.0", descripcion: "Amigdalitis crónica" },
  { codigo: "J38", descripcion: "Enfermedades de las cuerdas vocales y de la laringe, no clasificadas en otra parte" },
  { codigo: "J40", descripcion: "Bronquitis, no especificada como aguda o crónica" },
  { codigo: "J41", descripcion: "Bronquitis crónica simple y mucopurulenta" },
  { codigo: "J44", descripcion: "Otras enfermedades pulmonares obstructivas crónicas" },
  { codigo: "J44.0", descripcion: "EPOC con infección respiratoria aguda del tracto respiratorio inferior" },
  { codigo: "J44.1", descripcion: "EPOC con exacerbación aguda, no especificada" },
  { codigo: "J44.9", descripcion: "EPOC, no especificada" },
  { codigo: "J45", descripcion: "Asma" },
  { codigo: "J45.0", descripcion: "Asma predominantemente alérgica" },
  { codigo: "J45.1", descripcion: "Asma no alérgica" },
  { codigo: "J45.9", descripcion: "Asma, no especificada" },
  { codigo: "J46", descripcion: "Estado asmático" },
  { codigo: "J47", descripcion: "Bronquiectasia" },
  { codigo: "J60", descripcion: "Neumoconiosis de los mineros del carbón" },
  { codigo: "J69.0", descripcion: "Neumonitis debida a aspiración de alimento y vómito" },
  { codigo: "J80", descripcion: "Síndrome de dificultad respiratoria del adulto" },
  { codigo: "J81", descripcion: "Edema pulmonar" },
  { codigo: "J84.1", descripcion: "Otras enfermedades pulmonares intersticiales con fibrosis" },
  { codigo: "J86", descripcion: "Piotórax" },
  { codigo: "J90", descripcion: "Derrame pleural, no clasificado en otra parte" },
  { codigo: "J93", descripcion: "Neumotórax" },
  { codigo: "J96", descripcion: "Insuficiencia respiratoria, no clasificada en otra parte" },
  { codigo: "J96.0", descripcion: "Insuficiencia respiratoria aguda" },
  { codigo: "J96.1", descripcion: "Insuficiencia respiratoria crónica" },
  { codigo: "J98.0", descripcion: "Enfermedades del bronquio, no clasificadas en otra parte" },

  // ──────────────────────────────────────────────────────────────────────────
  // Capítulo XI: Enfermedades del sistema digestivo (K00-K93)
  // ──────────────────────────────────────────────────────────────────────────
  { codigo: "K01", descripcion: "Dientes incluidos e impactados" },
  { codigo: "K02", descripcion: "Caries dental" },
  { codigo: "K04", descripcion: "Enfermedades de la pulpa y de los tejidos periapicales" },
  { codigo: "K05", descripcion: "Gingivitis y enfermedades periodontales" },
  { codigo: "K07", descripcion: "Anomalías dentofaciales [inclusive las maloclusiones]" },
  { codigo: "K20", descripcion: "Esofagitis" },
  { codigo: "K21", descripcion: "Enfermedad por reflujo gastroesofágico" },
  { codigo: "K21.0", descripcion: "Enfermedad por reflujo gastroesofágico con esofagitis" },
  { codigo: "K21.9", descripcion: "Enfermedad por reflujo gastroesofágico sin esofagitis" },
  { codigo: "K22", descripcion: "Otras enfermedades del esófago" },
  { codigo: "K25", descripcion: "Úlcera gástrica" },
  { codigo: "K25.9", descripcion: "Úlcera gástrica, no especificada como aguda o crónica" },
  { codigo: "K26", descripcion: "Úlcera duodenal" },
  { codigo: "K26.9", descripcion: "Úlcera duodenal, no especificada como aguda o crónica" },
  { codigo: "K27", descripcion: "Úlcera péptica de sitio no especificado" },
  { codigo: "K29", descripcion: "Gastritis y duodenitis" },
  { codigo: "K29.5", descripcion: "Gastritis crónica, no especificada" },
  { codigo: "K30", descripcion: "Dispepsia" },
  { codigo: "K35", descripcion: "Apendicitis aguda" },
  { codigo: "K35.8", descripcion: "Apendicitis aguda, sin mención de peritonitis" },
  { codigo: "K36", descripcion: "Otras formas de apendicitis" },
  { codigo: "K37", descripcion: "Apendicitis, no especificada" },
  { codigo: "K40", descripcion: "Hernia inguinal" },
  { codigo: "K40.9", descripcion: "Hernia inguinal unilateral o no especificada, sin obstrucción ni gangrena" },
  { codigo: "K41", descripcion: "Hernia femoral" },
  { codigo: "K43", descripcion: "Hernia ventral" },
  { codigo: "K44", descripcion: "Hernia diafragmática" },
  { codigo: "K46", descripcion: "Hernia abdominal no especificada" },
  { codigo: "K50", descripcion: "Enfermedad de Crohn [enteritis regional]" },
  { codigo: "K51", descripcion: "Colitis ulcerativa" },
  { codigo: "K52", descripcion: "Otras colitis y gastroenteritis no infecciosas" },
  { codigo: "K56", descripcion: "Íleo paralítico y obstrucción intestinal sin hernia" },
  { codigo: "K57", descripcion: "Enfermedad diverticular del intestino" },
  { codigo: "K58", descripcion: "Síndrome del colon irritable" },
  { codigo: "K58.9", descripcion: "Síndrome del colon irritable sin diarrea" },
  { codigo: "K59.0", descripcion: "Estreñimiento" },
  { codigo: "K60", descripcion: "Fisura y fístula de las regiones anal y rectal" },
  { codigo: "K61", descripcion: "Absceso de las regiones anal y rectal" },
  { codigo: "K62", descripcion: "Otras enfermedades del recto y del ano" },
  { codigo: "K70", descripcion: "Enfermedad hepática alcohólica" },
  { codigo: "K70.3", descripcion: "Cirrosis hepática alcohólica" },
  { codigo: "K71", descripcion: "Enfermedad hepática tóxica" },
  { codigo: "K72", descripcion: "Insuficiencia hepática, no clasificada en otra parte" },
  { codigo: "K73", descripcion: "Hepatitis crónica, no clasificada en otra parte" },
  { codigo: "K74", descripcion: "Fibrosis y cirrosis del hígado" },
  { codigo: "K74.6", descripcion: "Otras formas de cirrosis del hígado y la no especificada" },
  { codigo: "K75", descripcion: "Otras enfermedades inflamatorias del hígado" },
  { codigo: "K76.0", descripcion: "Hígado graso, no clasificado en otra parte" },
  { codigo: "K80", descripcion: "Colelitiasis" },
  { codigo: "K80.0", descripcion: "Cálculo de la vesícula biliar con colecistitis aguda" },
  { codigo: "K80.1", descripcion: "Cálculo de la vesícula biliar con otra colecistitis" },
  { codigo: "K80.2", descripcion: "Cálculo de la vesícula biliar sin colecistitis" },
  { codigo: "K80.5", descripcion: "Cálculo del conducto biliar sin colangitis ni colecistitis" },
  { codigo: "K81", descripcion: "Colecistitis" },
  { codigo: "K85", descripcion: "Pancreatitis aguda" },
  { codigo: "K86.1", descripcion: "Otras pancreatitis crónicas" },
  { codigo: "K90", descripcion: "Malabsorción intestinal" },
  { codigo: "K92.1", descripcion: "Melena" },
  { codigo: "K92.2", descripcion: "Hemorragia gastrointestinal, no especificada" },

  // ──────────────────────────────────────────────────────────────────────────
  // Capítulo XII: Enfermedades de la piel y del tejido subcutáneo (L00-L99)
  // ──────────────────────────────────────────────────────────────────────────
  { codigo: "L01", descripcion: "Impétigo" },
  { codigo: "L02", descripcion: "Absceso cutáneo, furúnculo y carbunco" },
  { codigo: "L03", descripcion: "Celulitis" },
  { codigo: "L03.9", descripcion: "Celulitis, no especificada" },
  { codigo: "L04", descripcion: "Linfadenitis aguda" },
  { codigo: "L10", descripcion: "Pénfigo" },
  { codigo: "L12", descripcion: "Penfigoide" },
  { codigo: "L20", descripcion: "Dermatitis atópica" },
  { codigo: "L20.9", descripcion: "Dermatitis atópica, no especificada" },
  { codigo: "L21", descripcion: "Dermatitis seborreica" },
  { codigo: "L22", descripcion: "Dermatitis del pañal" },
  { codigo: "L23", descripcion: "Dermatitis alérgica de contacto" },
  { codigo: "L25", descripcion: "Dermatitis de contacto, no especificada" },
  { codigo: "L26", descripcion: "Dermatitis exfoliativa" },
  { codigo: "L27", descripcion: "Dermatitis debida a sustancias de uso interno" },
  { codigo: "L29", descripcion: "Prurito" },
  { codigo: "L30.9", descripcion: "Dermatitis, no especificada" },
  { codigo: "L40", descripcion: "Psoriasis" },
  { codigo: "L40.0", descripcion: "Psoriasis vulgar" },
  { codigo: "L41", descripcion: "Parapsoriasis" },
  { codigo: "L43", descripcion: "Liquen plano" },
  { codigo: "L50", descripcion: "Urticaria" },
  { codigo: "L50.0", descripcion: "Urticaria alérgica" },
  { codigo: "L50.9", descripcion: "Urticaria, no especificada" },
  { codigo: "L51", descripcion: "Eritema multiforme" },
  { codigo: "L53.9", descripcion: "Afección eritematosa, no especificada" },
  { codigo: "L57.0", descripcion: "Queratosis actínica" },
  { codigo: "L60", descripcion: "Trastornos de las uñas" },
  { codigo: "L63", descripcion: "Alopecia areata" },
  { codigo: "L64", descripcion: "Alopecia androgénica" },
  { codigo: "L70", descripcion: "Acné" },
  { codigo: "L70.0", descripcion: "Acné vulgar" },
  { codigo: "L71", descripcion: "Rosácea" },
  { codigo: "L72", descripcion: "Quiste folicular de la piel y del tejido subcutáneo" },
  { codigo: "L80", descripcion: "Vitiligo" },
  { codigo: "L89", descripcion: "Úlcera por presión" },
  { codigo: "L90.5", descripcion: "Cicatriz y fibrosis de la piel" },
  { codigo: "L91.0", descripcion: "Queloides" },
  { codigo: "L98.4", descripcion: "Úlcera crónica de la piel, no clasificada en otra parte" },

  // ──────────────────────────────────────────────────────────────────────────
  // Capítulo XIII: Enfermedades del sistema musculoesquelético (M00-M99)
  // ──────────────────────────────────────────────────────────────────────────
  { codigo: "M00", descripcion: "Artritis piógena" },
  { codigo: "M05", descripcion: "Artritis reumatoide seropositiva" },
  { codigo: "M06", descripcion: "Otras artritis reumatoides" },
  { codigo: "M06.9", descripcion: "Artritis reumatoide, no especificada" },
  { codigo: "M10", descripcion: "Gota" },
  { codigo: "M10.9", descripcion: "Gota, no especificada" },
  { codigo: "M13.9", descripcion: "Artritis, no especificada" },
  { codigo: "M15", descripcion: "Poliartrosis" },
  { codigo: "M16", descripcion: "Coxartrosis [artrosis de la cadera]" },
  { codigo: "M16.1", descripcion: "Coxartrosis primaria unilateral" },
  { codigo: "M17", descripcion: "Gonartrosis [artrosis de la rodilla]" },
  { codigo: "M17.1", descripcion: "Gonartrosis primaria unilateral" },
  { codigo: "M19", descripcion: "Otras artrosis" },
  { codigo: "M19.9", descripcion: "Artrosis, no especificada" },
  { codigo: "M20", descripcion: "Deformidades adquiridas de los dedos de la mano y del pie" },
  { codigo: "M23", descripcion: "Trastornos internos de la rodilla" },
  { codigo: "M25.5", descripcion: "Dolor en articulación" },
  { codigo: "M30", descripcion: "Poliarteritis nudosa y afecciones relacionadas" },
  { codigo: "M32", descripcion: "Lupus eritematoso sistémico" },
  { codigo: "M34", descripcion: "Esclerosis sistémica [esclerodermia]" },
  { codigo: "M40", descripcion: "Cifosis y lordosis" },
  { codigo: "M41", descripcion: "Escoliosis" },
  { codigo: "M42", descripcion: "Osteocondritis de la columna vertebral" },
  { codigo: "M43", descripcion: "Otras dorsopatías deformantes" },
  { codigo: "M45", descripcion: "Espondilitis anquilosante" },
  { codigo: "M47", descripcion: "Espondiloartrosis" },
  { codigo: "M48", descripcion: "Otras espondilopatías" },
  { codigo: "M50", descripcion: "Trastornos del disco cervical" },
  { codigo: "M51", descripcion: "Otros trastornos de los discos intervertebrales" },
  { codigo: "M54", descripcion: "Dorsalgia" },
  { codigo: "M54.2", descripcion: "Cervicalgia" },
  { codigo: "M54.5", descripcion: "Lumbalgia" },
  { codigo: "M54.4", descripcion: "Lumbago con ciática" },
  { codigo: "M60", descripcion: "Miositis" },
  { codigo: "M62", descripcion: "Otros trastornos de los músculos" },
  { codigo: "M65", descripcion: "Sinovitis y tenosinovitis" },
  { codigo: "M70", descripcion: "Trastornos de los tejidos blandos relacionados con el uso excesivo" },
  { codigo: "M72", descripcion: "Trastornos fibroblásticos" },
  { codigo: "M75.0", descripcion: "Síndrome del manguito rotatorio" },
  { codigo: "M79.3", descripcion: "Panniculitis" },
  { codigo: "M80", descripcion: "Osteoporosis con fractura patológica" },
  { codigo: "M81", descripcion: "Osteoporosis sin fractura patológica" },
  { codigo: "M81.0", descripcion: "Osteoporosis postmenopáusica" },
  { codigo: "M85", descripcion: "Otros trastornos de la densidad y de la estructura óseas" },
  { codigo: "M87", descripcion: "Osteonecrosis" },
  { codigo: "M89.9", descripcion: "Trastorno del hueso, no especificado" },

  // ──────────────────────────────────────────────────────────────────────────
  // Capítulo XIV: Enfermedades del sistema genitourinario (N00-N99)
  // ──────────────────────────────────────────────────────────────────────────
  { codigo: "N00", descripcion: "Síndrome nefrítico agudo" },
  { codigo: "N02", descripcion: "Hematuria recurrente y persistente" },
  { codigo: "N03", descripcion: "Síndrome nefrítico crónico" },
  { codigo: "N04", descripcion: "Síndrome nefrótico" },
  { codigo: "N05", descripcion: "Síndrome nefrítico no especificado" },
  { codigo: "N17", descripcion: "Insuficiencia renal aguda" },
  { codigo: "N17.9", descripcion: "Insuficiencia renal aguda, no especificada" },
  { codigo: "N18", descripcion: "Insuficiencia renal crónica" },
  { codigo: "N18.9", descripcion: "Insuficiencia renal crónica, no especificada" },
  { codigo: "N19", descripcion: "Insuficiencia renal no especificada" },
  { codigo: "N20", descripcion: "Cálculo del riñón y del uréter" },
  { codigo: "N20.0", descripcion: "Cálculo del riñón" },
  { codigo: "N20.1", descripcion: "Cálculo del uréter" },
  { codigo: "N21", descripcion: "Cálculo de las vías urinarias inferiores" },
  { codigo: "N23", descripcion: "Cólico renal, no especificado" },
  { codigo: "N25.0", descripcion: "Osteodistrofia renal" },
  { codigo: "N28.1", descripcion: "Quiste del riñón, adquirido" },
  { codigo: "N30", descripcion: "Cistitis" },
  { codigo: "N30.0", descripcion: "Cistitis aguda" },
  { codigo: "N30.1", descripcion: "Cistitis intersticial (crónica)" },
  { codigo: "N31", descripcion: "Disfunción neuromuscular de la vejiga" },
  { codigo: "N35", descripcion: "Estrechez uretral" },
  { codigo: "N36", descripcion: "Otros trastornos de la uretra" },
  { codigo: "N39.0", descripcion: "Infección de vías urinarias, sitio no especificado" },
  { codigo: "N40", descripcion: "Hiperplasia de la próstata" },
  { codigo: "N41", descripcion: "Enfermedades inflamatorias de la próstata" },
  { codigo: "N41.0", descripcion: "Prostatitis aguda" },
  { codigo: "N41.1", descripcion: "Prostatitis crónica" },
  { codigo: "N42.9", descripcion: "Trastorno de la próstata, no especificado" },
  { codigo: "N45", descripcion: "Orquitis y epididimitis" },
  { codigo: "N50", descripcion: "Otros trastornos de los órganos genitales masculinos" },
  { codigo: "N60", descripcion: "Displasia mamaria benigna" },
  { codigo: "N61", descripcion: "Trastornos inflamatorios de la mama" },
  { codigo: "N70", descripcion: "Salpingitis y ooforitis" },
  { codigo: "N71", descripcion: "Enfermedad inflamatoria del útero, excepto del cuello uterino" },
  { codigo: "N72", descripcion: "Enfermedad inflamatoria del cuello uterino" },
  { codigo: "N73", descripcion: "Otras enfermedades inflamatorias pélvicas femeninas" },
  { codigo: "N75", descripcion: "Enfermedades de la glándula de Bartholin" },
  { codigo: "N76", descripcion: "Otras enfermedades inflamatorias de la vagina y de la vulva" },
  { codigo: "N80", descripcion: "Endometriosis" },
  { codigo: "N81", descripcion: "Prolapso genital femenino" },
  { codigo: "N83", descripcion: "Trastornos no inflamatorios del ovario, de la trompa de Falopio y del ligamento ancho" },
  { codigo: "N84", descripcion: "Pólipo del tracto genital femenino" },
  { codigo: "N85", descripcion: "Otras enfermedades no inflamatorias del útero, excepto del cuello uterino" },
  { codigo: "N87", descripcion: "Displasia del cuello uterino" },
  { codigo: "N91", descripcion: "Menstruación ausente, escasa o rara" },
  { codigo: "N91.1", descripcion: "Amenorrea secundaria" },
  { codigo: "N92", descripcion: "Menstruación excesiva, frecuente o irregular" },
  { codigo: "N93", descripcion: "Otras hemorragias uterinas o vaginales anormales" },
  { codigo: "N94", descripcion: "Dolor y otras afecciones relacionadas con los órganos genitales femeninos y el ciclo menstrual" },
  { codigo: "N94.6", descripcion: "Dismenorrea, no especificada" },
  { codigo: "N95.1", descripcion: "Menopausia y estados menopáusicos femeninos" },
  { codigo: "N99.0", descripcion: "Insuficiencia renal consecutiva a procedimientos" },

  // ──────────────────────────────────────────────────────────────────────────
  // Capítulo XV: Embarazo, parto y puerperio (O00-O99)
  // ──────────────────────────────────────────────────────────────────────────
  { codigo: "O00", descripcion: "Embarazo ectópico" },
  { codigo: "O01", descripcion: "Mola hidatiforme" },
  { codigo: "O02", descripcion: "Otros productos anormales de la concepción" },
  { codigo: "O03", descripcion: "Aborto espontáneo" },
  { codigo: "O04", descripcion: "Aborto médico" },
  { codigo: "O06", descripcion: "Aborto no especificado" },
  { codigo: "O10", descripcion: "Hipertensión preexistente que complica el embarazo, el parto y el puerperio" },
  { codigo: "O11", descripcion: "Trastorno hipertensivo preexistente con proteinuria superpuesta" },
  { codigo: "O12", descripcion: "Edema y proteinuria gestacionales sin hipertensión" },
  { codigo: "O13", descripcion: "Hipertensión gestacional [inducida por el embarazo] sin proteinuria significativa" },
  { codigo: "O14", descripcion: "Hipertensión gestacional con proteinuria significativa" },
  { codigo: "O14.0", descripcion: "Preeclampsia moderada" },
  { codigo: "O14.1", descripcion: "Preeclampsia severa" },
  { codigo: "O15", descripcion: "Eclampsia" },
  { codigo: "O20", descripcion: "Hemorragia precoz del embarazo" },
  { codigo: "O21", descripcion: "Vómitos excesivos en el embarazo" },
  { codigo: "O24", descripcion: "Diabetes mellitus en el embarazo" },
  { codigo: "O26", descripcion: "Atención materna por otras afecciones principalmente relacionadas con el embarazo" },
  { codigo: "O30", descripcion: "Gestación múltiple" },
  { codigo: "O32", descripcion: "Atención materna por presentación anormal fetal conocida o presunta" },
  { codigo: "O34", descripcion: "Atención materna por anormalidades conocidas o presuntas de los órganos pélvicos" },
  { codigo: "O36", descripcion: "Atención materna por otros problemas fetales conocidos o presuntos" },
  { codigo: "O40", descripcion: "Polihidramnios" },
  { codigo: "O41.0", descripcion: "Oligohidramnios" },
  { codigo: "O42", descripcion: "Ruptura prematura de las membranas" },
  { codigo: "O44", descripcion: "Placenta previa" },
  { codigo: "O45", descripcion: "Desprendimiento prematuro de la placenta [abruptio placentae]" },
  { codigo: "O60", descripcion: "Trabajo de parto pretérmino" },
  { codigo: "O63", descripcion: "Trabajo de parto prolongado" },
  { codigo: "O69", descripcion: "Trabajo de parto y parto complicados por problemas del cordón umbilical" },
  { codigo: "O80", descripcion: "Parto único espontáneo" },
  { codigo: "O82", descripcion: "Parto único por cesárea" },
  { codigo: "O85", descripcion: "Sepsis puerperal" },
  { codigo: "O86", descripcion: "Otras infecciones puerperales" },
  { codigo: "O87", descripcion: "Complicaciones venosas en el puerperio" },
  { codigo: "O88", descripcion: "Embolia obstétrica" },
  { codigo: "O90", descripcion: "Complicaciones del puerperio, no clasificadas en otra parte" },
  { codigo: "O92", descripcion: "Otros trastornos de la mama y de la lactancia asociados al parto" },

  // ──────────────────────────────────────────────────────────────────────────
  // Capítulo XVI: Afecciones originadas en el período perinatal (P00-P96)
  // ──────────────────────────────────────────────────────────────────────────
  { codigo: "P05", descripcion: "Crecimiento fetal lento y desnutrición fetal" },
  { codigo: "P07", descripcion: "Trastornos relacionados con duración corta de la gestación y bajo peso al nacer" },
  { codigo: "P10", descripcion: "Laceración y hemorragia intracraneal debidas a traumatismo del nacimiento" },
  { codigo: "P20", descripcion: "Hipoxia intrauterina" },
  { codigo: "P21", descripcion: "Asfixia del nacimiento" },
  { codigo: "P22", descripcion: "Dificultad respiratoria del recién nacido" },
  { codigo: "P23", descripcion: "Neumonía congénita" },
  { codigo: "P24", descripcion: "Síndromes de aspiración neonatal" },
  { codigo: "P27.1", descripcion: "Displasia broncopulmonar originada en el período perinatal" },
  { codigo: "P29.1", descripcion: "Neonatal neonatocardia (bradycardia)" },
  { codigo: "P36", descripcion: "Septicemia bacteriana del recién nacido" },
  { codigo: "P52", descripcion: "Hemorragia intracraneal no traumática del feto y del recién nacido" },
  { codigo: "P59", descripcion: "Ictericia neonatal por otras causas especificadas y por las no especificadas" },
  { codigo: "P70.1", descripcion: "Síndrome del recién nacido de madre diabética" },
  { codigo: "P80.9", descripcion: "Hipotermia del recién nacido, no especificada" },
  { codigo: "P96.1", descripcion: "Síndrome de abstinencia neonatal de la madre drogadicta" },

  // ──────────────────────────────────────────────────────────────────────────
  // Capítulo XVII: Malformaciones congénitas (Q00-Q99)
  // ──────────────────────────────────────────────────────────────────────────
  { codigo: "Q00", descripcion: "Anencefalia y malformaciones similares" },
  { codigo: "Q03", descripcion: "Hidrocefalia congénita" },
  { codigo: "Q05", descripcion: "Espina bífida" },
  { codigo: "Q20", descripcion: "Malformaciones congénitas de las cámaras cardíacas y sus conexiones" },
  { codigo: "Q21", descripcion: "Malformaciones congénitas de los tabiques cardíacos" },
  { codigo: "Q21.0", descripcion: "Defecto del tabique ventricular" },
  { codigo: "Q21.1", descripcion: "Defecto del tabique auricular" },
  { codigo: "Q25.0", descripcion: "Conducto arterioso persistente" },
  { codigo: "Q27.0", descripcion: "Ausencia e hipoplasia congénitas de la arteria umbilical" },
  { codigo: "Q33.6", descripcion: "Pulmón congénitamente reducido" },
  { codigo: "Q35", descripcion: "Fisura del paladar" },
  { codigo: "Q36", descripcion: "Labio hendido [labio leporino]" },
  { codigo: "Q37", descripcion: "Fisura del paladar con labio hendido" },
  { codigo: "Q39.0", descripcion: "Atresia del esófago sin fístula" },
  { codigo: "Q42", descripcion: "Ausencia, atresia y estenosis congénitas del intestino grueso" },
  { codigo: "Q43.1", descripcion: "Enfermedad de Hirschsprung" },
  { codigo: "Q44.2", descripcion: "Quiste de las vías biliares" },
  { codigo: "Q53", descripcion: "Testículo no descendido" },
  { codigo: "Q54", descripcion: "Hipospadia" },
  { codigo: "Q65", descripcion: "Deformidades congénitas de la cadera" },
  { codigo: "Q66", descripcion: "Deformidades congénitas del pie" },
  { codigo: "Q90", descripcion: "Síndrome de Down" },
  { codigo: "Q93.5", descripcion: "Deleciones de otras regiones de los autosomas" },
  { codigo: "Q96", descripcion: "Síndrome de Turner" },
  { codigo: "Q98.0", descripcion: "Síndrome de Klinefelter, cariotipo 47,XXY" },

  // ──────────────────────────────────────────────────────────────────────────
  // Capítulo XVIII: Síntomas, signos y hallazgos anormales (R00-R99)
  // ──────────────────────────────────────────────────────────────────────────
  { codigo: "R00.0", descripcion: "Taquicardia, no especificada" },
  { codigo: "R00.1", descripcion: "Bradicardia, no especificada" },
  { codigo: "R00.8", descripcion: "Otras anormalidades y las no especificadas del ritmo cardíaco" },
  { codigo: "R01.1", descripcion: "Soplo cardíaco benigno (inocente)" },
  { codigo: "R04.2", descripcion: "Hemoptisis" },
  { codigo: "R05", descripcion: "Tos" },
  { codigo: "R06.0", descripcion: "Disnea" },
  { codigo: "R06.1", descripcion: "Estridor" },
  { codigo: "R06.2", descripcion: "Sibilancias" },
  { codigo: "R07", descripcion: "Dolor de garganta y en el pecho" },
  { codigo: "R07.4", descripcion: "Dolor en el pecho, no especificado" },
  { codigo: "R10", descripcion: "Dolor abdominal y pélvico" },
  { codigo: "R10.4", descripcion: "Otros dolores abdominales y los no especificados" },
  { codigo: "R11", descripcion: "Náusea y vómito" },
  { codigo: "R12", descripcion: "Acidez" },
  { codigo: "R13", descripcion: "Disfagia" },
  { codigo: "R14", descripcion: "Flatulencia y afecciones afines" },
  { codigo: "R15", descripcion: "Incontinencia fecal" },
  { codigo: "R17", descripcion: "Ictericia no especificada" },
  { codigo: "R18", descripcion: "Ascitis" },
  { codigo: "R20", descripcion: "Trastornos de la sensibilidad cutánea" },
  { codigo: "R25", descripcion: "Movimientos involuntarios anormales" },
  { codigo: "R30.9", descripcion: "Dolor asociado con la micción, no especificado" },
  { codigo: "R32", descripcion: "Incontinencia urinaria no especificada" },
  { codigo: "R33", descripcion: "Retención de orina" },
  { codigo: "R35", descripcion: "Poliuria" },
  { codigo: "R39.1", descripcion: "Dificultad en la micción" },
  { codigo: "R40", descripcion: "Somnolencia, estupor y coma" },
  { codigo: "R41.3", descripcion: "Otras amnesias" },
  { codigo: "R42", descripcion: "Vértigo" },
  { codigo: "R43", descripcion: "Trastornos del olfato y del gusto" },
  { codigo: "R44", descripcion: "Otros síntomas y signos que involucran las sensaciones y percepciones generales" },
  { codigo: "R45.1", descripcion: "Agitación e inquietud" },
  { codigo: "R47.0", descripcion: "Disfasia y afasia" },
  { codigo: "R50.9", descripcion: "Fiebre, no especificada" },
  { codigo: "R51", descripcion: "Cefalea" },
  { codigo: "R52.9", descripcion: "Dolor, no especificado" },
  { codigo: "R53", descripcion: "Malestar general y fatiga" },
  { codigo: "R55", descripcion: "Síncope y colapso" },
  { codigo: "R56", descripcion: "Convulsiones, no clasificadas en otra parte" },
  { codigo: "R57.0", descripcion: "Choque cardiogénico" },
  { codigo: "R57.9", descripcion: "Choque, no especificado" },
  { codigo: "R58", descripcion: "Hemorragia, no clasificada en otra parte" },
  { codigo: "R60.9", descripcion: "Edema, no especificado" },
  { codigo: "R63.0", descripcion: "Anorexia" },
  { codigo: "R63.4", descripcion: "Pérdida anormal de peso" },
  { codigo: "R68.9", descripcion: "Síntoma y signo general, no especificado" },
  { codigo: "R73.0", descripcion: "Prueba de glucosa anormal" },
  { codigo: "R73.09", descripcion: "Prediabetes" },
  { codigo: "R79.8", descripcion: "Otros hallazgos especificados de hallazgos anormales en examen de sangre" },

  // ──────────────────────────────────────────────────────────────────────────
  // Capítulo XIX: Traumatismos, envenenamientos y consecuencias (S00-T98)
  // ──────────────────────────────────────────────────────────────────────────
  { codigo: "S00", descripcion: "Traumatismo superficial de la cabeza" },
  { codigo: "S01", descripcion: "Herida de la cabeza" },
  { codigo: "S02", descripcion: "Fractura del cráneo y de los huesos de la cara" },
  { codigo: "S06", descripcion: "Traumatismo intracraneal" },
  { codigo: "S06.0", descripcion: "Conmoción cerebral" },
  { codigo: "S06.3", descripcion: "Contusión y laceración cerebral focal" },
  { codigo: "S09.9", descripcion: "Traumatismo de la cabeza, no especificado" },
  { codigo: "S10", descripcion: "Traumatismo superficial del cuello" },
  { codigo: "S12", descripcion: "Fractura del cuello" },
  { codigo: "S13.4", descripcion: "Esguince y torcedura de la columna cervical" },
  { codigo: "S20", descripcion: "Traumatismo superficial del tórax" },
  { codigo: "S22", descripcion: "Fractura de costilla(s), esternón y de la columna torácica" },
  { codigo: "S27.0", descripcion: "Neumotórax traumático" },
  { codigo: "S27.1", descripcion: "Hemotórax traumático" },
  { codigo: "S30", descripcion: "Traumatismo superficial del abdomen, de la región lumbosacra y de la pelvis" },
  { codigo: "S32", descripcion: "Fractura de la columna lumbar y de la pelvis" },
  { codigo: "S36", descripcion: "Traumatismo de órganos intraabdominales" },
  { codigo: "S40", descripcion: "Traumatismo superficial del hombro y del brazo" },
  { codigo: "S42", descripcion: "Fractura del hombro y del brazo" },
  { codigo: "S42.0", descripcion: "Fractura de la clavícula" },
  { codigo: "S42.2", descripcion: "Fractura de la diáfisis del húmero" },
  { codigo: "S50", descripcion: "Traumatismo superficial del antebrazo" },
  { codigo: "S52", descripcion: "Fractura del antebrazo" },
  { codigo: "S52.5", descripcion: "Fractura de la epífisis inferior del radio" },
  { codigo: "S60", descripcion: "Traumatismo superficial de la muñeca y de la mano" },
  { codigo: "S62", descripcion: "Fractura a nivel de la muñeca y de la mano" },
  { codigo: "S70", descripcion: "Traumatismo superficial de la cadera y del muslo" },
  { codigo: "S72", descripcion: "Fractura del fémur" },
  { codigo: "S72.0", descripcion: "Fractura del cuello del fémur" },
  { codigo: "S80", descripcion: "Traumatismo superficial de la pierna" },
  { codigo: "S82", descripcion: "Fractura de la pierna, inclusive del tobillo" },
  { codigo: "S82.0", descripcion: "Fractura de la rótula" },
  { codigo: "S82.6", descripcion: "Fractura del maléolo externo" },
  { codigo: "S90", descripcion: "Traumatismo superficial del tobillo y del pie" },
  { codigo: "S92", descripcion: "Fractura del pie, excepto del tobillo" },
  { codigo: "T07", descripcion: "Traumatismos múltiples, no especificados" },
  { codigo: "T14.0", descripcion: "Herida de sitio del cuerpo no especificado" },
  { codigo: "T14.1", descripcion: "Fractura de sitio del cuerpo no especificado" },
  { codigo: "T20", descripcion: "Quemadura y corrosión de la cabeza y del cuello" },
  { codigo: "T21", descripcion: "Quemadura y corrosión del tronco" },
  { codigo: "T30", descripcion: "Quemadura y corrosión de región del cuerpo no especificada" },
  { codigo: "T36", descripcion: "Envenenamiento por antibióticos sistémicos" },
  { codigo: "T39", descripcion: "Envenenamiento por analgésicos antipiréticos y antirreumáticos no opioides" },
  { codigo: "T45.1", descripcion: "Envenenamiento por agentes antineoplásicos e inmunosupresores" },
  { codigo: "T46.0", descripcion: "Envenenamiento por glucósidos cardíacos y drogas de acción similar" },
  { codigo: "T51", descripcion: "Efectos tóxicos del alcohol" },
  { codigo: "T57.0", descripcion: "Efectos tóxicos del arsénico y sus compuestos" },
  { codigo: "T65.2", descripcion: "Efectos tóxicos del tabaco y la nicotina" },
  { codigo: "T71", descripcion: "Asfixia" },
  { codigo: "T75.1", descripcion: "Ahogamiento y sumersión no fatales" },
  { codigo: "T78.0", descripcion: "Choque anafiláctico" },
  { codigo: "T78.1", descripcion: "Otras reacciones alérgicas ante alimentos" },
  { codigo: "T78.4", descripcion: "Alergia, no especificada" },
  { codigo: "T79.4", descripcion: "Choque traumático" },
  { codigo: "T81.0", descripcion: "Hemorragia y hematoma que complican un procedimiento, NCOP" },
  { codigo: "T81.4", descripcion: "Infección consecutiva a procedimiento, NCOP" },
  { codigo: "T82.8", descripcion: "Otras complicaciones de prótesis, implantes e injertos cardíacos y vasculares" },
  { codigo: "T85.7", descripcion: "Infección y reacción inflamatoria debida a otros dispositivos e implantes internos" },
  { codigo: "T88.5", descripcion: "Otras complicaciones de la anestesia" },
  { codigo: "T88.7", descripcion: "Efecto adverso no especificado de un fármaco o droga" },

  // ──────────────────────────────────────────────────────────────────────────
  // Capítulo XX: Causas externas de morbilidad y mortalidad (V01-Y98)
  // ──────────────────────────────────────────────────────────────────────────
  { codigo: "V01", descripcion: "Peatón lesionado por colisión con un vehículo de pedal" },
  { codigo: "V03", descripcion: "Peatón lesionado por colisión con un automóvil" },
  { codigo: "V09.3", descripcion: "Peatón lesionado en accidente de tránsito no especificado" },
  { codigo: "V40", descripcion: "Ocupante de automóvil lesionado por colisión con un vehículo de pedal" },
  { codigo: "V49.9", descripcion: "Ocupante de automóvil lesionado en accidente de tránsito no especificado" },
  { codigo: "W01", descripcion: "Caída en el mismo nivel por deslizamiento, tropezón y traspié" },
  { codigo: "W06", descripcion: "Caída de una cama" },
  { codigo: "W10", descripcion: "Caída en o desde escaleras o escalones" },
  { codigo: "W18", descripcion: "Otras caídas en el mismo nivel" },
  { codigo: "W19", descripcion: "Caída no especificada" },
  { codigo: "W54", descripcion: "Mordedura o ataque de perro" },
  { codigo: "X04", descripcion: "Exposición a ignición de material muy inflamable" },
  { codigo: "X40", descripcion: "Envenenamiento accidental por y exposición a analgésicos, antipiréticos y antirreumáticos" },
  { codigo: "X41", descripcion: "Envenenamiento accidental por y exposición a anticonvulsionantes, sedantes, hipnóticos" },
  { codigo: "X44", descripcion: "Envenenamiento accidental por y exposición a otras drogas, medicamentos y sustancias biológicas" },
  { codigo: "X60", descripcion: "Autoenvenenamiento intencionado y exposición a analgésicos no opioides" },
  { codigo: "X70", descripcion: "Ahorcamiento, estrangulamiento e inanición intencionalmente autoinfligidos" },
  { codigo: "X84", descripcion: "Lesión autoinfligida intencionalmente por medios no especificados" },
  { codigo: "Y83", descripcion: "Intervención quirúrgica y otros procedimientos médicos como causa de reacción anormal" },
  { codigo: "Y84.6", descripcion: "Cateterismo uretral como causa de reacción anormal del paciente" },

  // ──────────────────────────────────────────────────────────────────────────
  // Capítulo XXI: Factores que influyen en el estado de salud (Z00-Z99)
  // ──────────────────────────────────────────────────────────────────────────
  { codigo: "Z00.0", descripcion: "Examen médico general" },
  { codigo: "Z00.1", descripcion: "Examen de rutina de salud del niño" },
  { codigo: "Z01.0", descripcion: "Examen de los ojos y de la visión" },
  { codigo: "Z01.1", descripcion: "Examen de los oídos y de la audición" },
  { codigo: "Z03.9", descripcion: "Observación y evaluación médica por razón no especificada" },
  { codigo: "Z08", descripcion: "Examen de seguimiento después del tratamiento por tumor maligno" },
  { codigo: "Z09", descripcion: "Examen de seguimiento después del tratamiento por otras afecciones" },
  { codigo: "Z11.3", descripcion: "Examen especial de detección de infecciones transmitidas predominantemente por vía sexual" },
  { codigo: "Z12.3", descripcion: "Examen especial de detección de tumores malignos de la mama" },
  { codigo: "Z12.4", descripcion: "Examen especial de detección de tumores malignos del cuello del útero" },
  { codigo: "Z21", descripcion: "Estado de infección asintomática por el VIH" },
  { codigo: "Z23", descripcion: "Necesidad de inmunización contra enfermedades bacterianas individuales" },
  { codigo: "Z27", descripcion: "Necesidad de inmunización contra combinaciones de enfermedades infecciosas" },
  { codigo: "Z30", descripcion: "Atención para la anticoncepción" },
  { codigo: "Z34", descripcion: "Supervisión de embarazo normal" },
  { codigo: "Z36", descripcion: "Diagnóstico prenatal" },
  { codigo: "Z37.0", descripcion: "Producto único, nacido vivo" },
  { codigo: "Z37.2", descripcion: "Gemelos, ambos nacidos vivos" },
  { codigo: "Z38.0", descripcion: "Neonato único, nacido en hospital" },
  { codigo: "Z39.1", descripcion: "Cuidado y examen de la madre que da de lactar" },
  { codigo: "Z41.2", descripcion: "Circuncisión de rutina" },
  { codigo: "Z45.0", descripcion: "Ajuste y control de marcapasos cardíaco" },
  { codigo: "Z48.0", descripcion: "Atención para retirar puntos de sutura" },
  { codigo: "Z51.0", descripcion: "Radioterapia" },
  { codigo: "Z51.1", descripcion: "Sesión de quimioterapia por tumor" },
  { codigo: "Z53.0", descripcion: "Procedimiento no realizado por contraindicación" },
  { codigo: "Z54.0", descripcion: "Convalecencia consecutiva a la cirugía" },
  { codigo: "Z55", descripcion: "Problemas relacionados con la educación y la alfabetización" },
  { codigo: "Z56", descripcion: "Problemas relacionados con el empleo y el desempleo" },
  { codigo: "Z57", descripcion: "Exposición ocupacional a factores de riesgo" },
  { codigo: "Z60", descripcion: "Problemas relacionados con el ambiente social" },
  { codigo: "Z63.0", descripcion: "Problemas en la relación con el cónyuge o pareja" },
  { codigo: "Z63.4", descripcion: "Desaparición y fallecimiento de un miembro de la familia" },
  { codigo: "Z71.1", descripcion: "Persona que teme estar enferma cuando no haya diagnóstico" },
  { codigo: "Z74.0", descripcion: "Necesidad de asistencia a causa de movilidad disminuida" },
  { codigo: "Z75.1", descripcion: "Persona en lista de espera de servicios de salud" },
  { codigo: "Z76.0", descripcion: "Prescripción y dispensación de repetición de medicamentos" },
  { codigo: "Z76.2", descripcion: "Supervisión de salud de otro niño sano" },
  { codigo: "Z79.1", descripcion: "Uso continuado (crónico) de anticoagulantes" },
  { codigo: "Z79.4", descripcion: "Uso de insulina a largo plazo" },
  { codigo: "Z82.3", descripcion: "Historia familiar de apoplejía" },
  { codigo: "Z85.0", descripcion: "Historia personal de tumor maligno del aparato digestivo" },
  { codigo: "Z86.5", descripcion: "Historia personal de otras enfermedades del sistema circulatorio" },
  { codigo: "Z87.1", descripcion: "Historia personal de enfermedades del aparato digestivo" },
  { codigo: "Z88.0", descripcion: "Alergia a la penicilina" },
  { codigo: "Z88.1", descripcion: "Alergia a otro antibiótico" },
  { codigo: "Z88.6", descripcion: "Alergia a analgésicos" },
  { codigo: "Z91.0", descripcion: "Alergia a agentes distintos de los fármacos y las sustancias biológicas" },
  { codigo: "Z95.0", descripcion: "Presencia de marcapasos cardíaco" },
  { codigo: "Z95.1", descripcion: "Presencia de derivación aortacoronaria" },
  { codigo: "Z96.6", descripcion: "Presencia de prótesis ortopédicas articulares" },
  { codigo: "Z98.0", descripcion: "Estado de derivación intestinal y anastomosis" },
  { codigo: "Z99.1", descripcion: "Dependencia de respirador" },
  { codigo: "Z99.2", descripcion: "Dependencia de diálisis renal" }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { CIE10_CATALOGO };
}
