// Catálogo CIE-10 — ~400 códigos organizados por capítulo
const CATALOGO_CIE10 = [
  // ═══ Cap I: A00-B99 Enfermedades infecciosas y parasitarias ═══
  {codigo:'A00',descripcion:'Cólera',capitulo:'I'},{codigo:'A01.0',descripcion:'Fiebre tifoidea',capitulo:'I'},
  {codigo:'A02.0',descripcion:'Salmonelosis',capitulo:'I'},{codigo:'A03.9',descripcion:'Shigelosis no especificada',capitulo:'I'},
  {codigo:'A04.7',descripcion:'Enterocolitis por Clostridium difficile',capitulo:'I'},{codigo:'A05.9',descripcion:'Intoxicación alimentaria bacteriana',capitulo:'I'},
  {codigo:'A06.0',descripcion:'Disentería amebiana aguda',capitulo:'I'},{codigo:'A08.0',descripcion:'Enteritis por rotavirus',capitulo:'I'},
  {codigo:'A09',descripcion:'Diarrea y gastroenteritis infecciosa',capitulo:'I'},{codigo:'A15.0',descripcion:'Tuberculosis pulmonar confirmada',capitulo:'I'},
  {codigo:'A16.9',descripcion:'Tuberculosis respiratoria no especificada',capitulo:'I'},{codigo:'A37.9',descripcion:'Tos ferina no especificada',capitulo:'I'},
  {codigo:'A38',descripcion:'Escarlatina',capitulo:'I'},{codigo:'A39.0',descripcion:'Meningitis meningocócica',capitulo:'I'},
  {codigo:'A41.9',descripcion:'Septicemia no especificada',capitulo:'I'},{codigo:'A46',descripcion:'Erisipela',capitulo:'I'},
  {codigo:'A49.9',descripcion:'Infección bacteriana no especificada',capitulo:'I'},{codigo:'A50.9',descripcion:'Sífilis congénita',capitulo:'I'},
  {codigo:'A53.9',descripcion:'Sífilis no especificada',capitulo:'I'},{codigo:'A54.9',descripcion:'Infección gonocócica no especificada',capitulo:'I'},
  {codigo:'A56.2',descripcion:'Infección por clamidia no especificada',capitulo:'I'},{codigo:'A60.0',descripcion:'Herpes genital',capitulo:'I'},
  {codigo:'A69.2',descripcion:'Enfermedad de Lyme',capitulo:'I'},{codigo:'A87.9',descripcion:'Meningitis viral no especificada',capitulo:'I'},
  {codigo:'B00.9',descripcion:'Infección herpética no especificada',capitulo:'I'},{codigo:'B01.9',descripcion:'Varicela sin complicaciones',capitulo:'I'},
  {codigo:'B02.9',descripcion:'Herpes zóster sin complicaciones',capitulo:'I'},{codigo:'B05.9',descripcion:'Sarampión sin complicaciones',capitulo:'I'},
  {codigo:'B06.9',descripcion:'Rubéola sin complicaciones',capitulo:'I'},{codigo:'B07',descripcion:'Verrugas víricas',capitulo:'I'},
  {codigo:'B15.9',descripcion:'Hepatitis A sin coma hepático',capitulo:'I'},{codigo:'B16.9',descripcion:'Hepatitis B aguda sin agente delta',capitulo:'I'},
  {codigo:'B17.1',descripcion:'Hepatitis C aguda',capitulo:'I'},{codigo:'B18.1',descripcion:'Hepatitis B crónica',capitulo:'I'},
  {codigo:'B18.2',descripcion:'Hepatitis C crónica',capitulo:'I'},{codigo:'B20',descripcion:'Enfermedad por VIH',capitulo:'I'},
  {codigo:'B24',descripcion:'Enfermedad por VIH sin especificar',capitulo:'I'},{codigo:'B34.9',descripcion:'Infección viral no especificada',capitulo:'I'},
  {codigo:'B35.1',descripcion:'Tiña de las uñas (onicomicosis)',capitulo:'I'},{codigo:'B35.3',descripcion:'Tiña del pie',capitulo:'I'},
  {codigo:'B36.0',descripcion:'Pitiriasis versicolor',capitulo:'I'},{codigo:'B37.0',descripcion:'Estomatitis candidiásica',capitulo:'I'},
  {codigo:'B37.3',descripcion:'Candidiasis de la vulva y vagina',capitulo:'I'},{codigo:'B37.9',descripcion:'Candidiasis no especificada',capitulo:'I'},
  {codigo:'B50.9',descripcion:'Paludismo por P. falciparum',capitulo:'I'},{codigo:'B54',descripcion:'Paludismo no especificado',capitulo:'I'},
  {codigo:'B65.1',descripcion:'Esquistosomiasis',capitulo:'I'},{codigo:'B69.0',descripcion:'Cisticercosis del SNC',capitulo:'I'},
  {codigo:'B73',descripcion:'Oncocercosis',capitulo:'I'},{codigo:'B76.9',descripcion:'Anquilostomiasis no especificada',capitulo:'I'},
  {codigo:'B77.9',descripcion:'Ascariasis no especificada',capitulo:'I'},{codigo:'B80',descripcion:'Enterobiasis (oxiuriasis)',capitulo:'I'},
  {codigo:'B82.9',descripcion:'Parasitosis intestinal no especificada',capitulo:'I'},{codigo:'B86',descripcion:'Escabiosis (sarna)',capitulo:'I'},
  {codigo:'B89',descripcion:'Enfermedad parasitaria no especificada',capitulo:'I'},

  // ═══ Cap II: C00-D48 Neoplasias ═══
  {codigo:'C16.9',descripcion:'Neoplasia maligna del estómago',capitulo:'II'},{codigo:'C18.9',descripcion:'Neoplasia maligna del colon',capitulo:'II'},
  {codigo:'C20',descripcion:'Neoplasia maligna del recto',capitulo:'II'},{codigo:'C22.0',descripcion:'Carcinoma hepatocelular',capitulo:'II'},
  {codigo:'C25.9',descripcion:'Neoplasia maligna del páncreas',capitulo:'II'},{codigo:'C34.9',descripcion:'Neoplasia maligna del bronquio/pulmón',capitulo:'II'},
  {codigo:'C43.9',descripcion:'Melanoma maligno de piel',capitulo:'II'},{codigo:'C44.9',descripcion:'Neoplasia maligna de piel (no melanoma)',capitulo:'II'},
  {codigo:'C50.9',descripcion:'Neoplasia maligna de mama',capitulo:'II'},{codigo:'C53.9',descripcion:'Neoplasia maligna del cuello uterino',capitulo:'II'},
  {codigo:'C54.1',descripcion:'Neoplasia maligna del endometrio',capitulo:'II'},{codigo:'C56',descripcion:'Neoplasia maligna del ovario',capitulo:'II'},
  {codigo:'C61',descripcion:'Neoplasia maligna de próstata',capitulo:'II'},{codigo:'C64',descripcion:'Neoplasia maligna del riñón',capitulo:'II'},
  {codigo:'C67.9',descripcion:'Neoplasia maligna de vejiga',capitulo:'II'},{codigo:'C71.9',descripcion:'Neoplasia maligna del encéfalo',capitulo:'II'},
  {codigo:'C73',descripcion:'Neoplasia maligna de tiroides',capitulo:'II'},{codigo:'C76.0',descripcion:'Neoplasia maligna de cabeza/cuello',capitulo:'II'},
  {codigo:'C80.9',descripcion:'Neoplasia maligna sitio no especificado',capitulo:'II'},{codigo:'C85.9',descripcion:'Linfoma no Hodgkin',capitulo:'II'},
  {codigo:'C90.0',descripcion:'Mieloma múltiple',capitulo:'II'},{codigo:'C91.0',descripcion:'Leucemia linfoblástica aguda',capitulo:'II'},
  {codigo:'C92.0',descripcion:'Leucemia mieloide aguda',capitulo:'II'},{codigo:'D12.6',descripcion:'Pólipo del colon',capitulo:'II'},
  {codigo:'D17.9',descripcion:'Lipoma',capitulo:'II'},{codigo:'D22.9',descripcion:'Nevo melanocítico',capitulo:'II'},
  {codigo:'D25.9',descripcion:'Leiomioma uterino (mioma)',capitulo:'II'},{codigo:'D27',descripcion:'Neoplasia benigna del ovario',capitulo:'II'},
  {codigo:'D32.9',descripcion:'Meningioma',capitulo:'II'},{codigo:'D48.9',descripcion:'Neoplasia comportamiento incierto',capitulo:'II'},

  // ═══ Cap III: D50-D89 Enfermedades de la sangre ═══
  {codigo:'D50.0',descripcion:'Anemia ferropénica por pérdida de sangre',capitulo:'III'},{codigo:'D50.9',descripcion:'Anemia por deficiencia de hierro',capitulo:'III'},
  {codigo:'D51.0',descripcion:'Anemia por deficiencia de vitamina B12',capitulo:'III'},{codigo:'D52.9',descripcion:'Anemia por deficiencia de folatos',capitulo:'III'},
  {codigo:'D53.9',descripcion:'Anemia nutricional no especificada',capitulo:'III'},{codigo:'D56.1',descripcion:'Beta talasemia',capitulo:'III'},
  {codigo:'D56.9',descripcion:'Talasemia no especificada',capitulo:'III'},{codigo:'D57.1',descripcion:'Anemia de células falciformes',capitulo:'III'},
  {codigo:'D58.9',descripcion:'Anemia hemolítica hereditaria',capitulo:'III'},{codigo:'D61.9',descripcion:'Anemia aplásica no especificada',capitulo:'III'},
  {codigo:'D64.9',descripcion:'Anemia no especificada',capitulo:'III'},{codigo:'D65',descripcion:'Coagulación intravascular diseminada',capitulo:'III'},
  {codigo:'D66',descripcion:'Hemofilia A',capitulo:'III'},{codigo:'D68.9',descripcion:'Trastorno de coagulación no especificado',capitulo:'III'},
  {codigo:'D69.3',descripcion:'Púrpura trombocitopénica idiopática',capitulo:'III'},{codigo:'D69.6',descripcion:'Trombocitopenia no especificada',capitulo:'III'},
  {codigo:'D70',descripcion:'Agranulocitosis (neutropenia)',capitulo:'III'},{codigo:'D72.8',descripcion:'Otros trastornos de leucocitos',capitulo:'III'},
  {codigo:'D80.9',descripcion:'Inmunodeficiencia no especificada',capitulo:'III'},{codigo:'D89.9',descripcion:'Trastorno del mecanismo inmunitario',capitulo:'III'},

  // ═══ Cap IV: E00-E90 Enfermedades endocrinas/metabólicas ═══
  {codigo:'E00.9',descripcion:'Síndrome congénito por deficiencia de yodo',capitulo:'IV'},{codigo:'E01.2',descripcion:'Bocio por deficiencia de yodo',capitulo:'IV'},
  {codigo:'E03.9',descripcion:'Hipotiroidismo no especificado',capitulo:'IV'},{codigo:'E04.9',descripcion:'Bocio no tóxico no especificado',capitulo:'IV'},
  {codigo:'E05.9',descripcion:'Tirotoxicosis (hipertiroidismo)',capitulo:'IV'},{codigo:'E06.3',descripcion:'Tiroiditis autoinmune (Hashimoto)',capitulo:'IV'},
  {codigo:'E10.9',descripcion:'Diabetes mellitus tipo 1',capitulo:'IV'},{codigo:'E11.9',descripcion:'Diabetes mellitus tipo 2',capitulo:'IV'},
  {codigo:'E11.2',descripcion:'DM tipo 2 con complicación renal',capitulo:'IV'},{codigo:'E11.3',descripcion:'DM tipo 2 con complicación oftálmica',capitulo:'IV'},
  {codigo:'E11.4',descripcion:'DM tipo 2 con complicación neurológica',capitulo:'IV'},{codigo:'E11.5',descripcion:'DM tipo 2 con complicación circulatoria',capitulo:'IV'},
  {codigo:'E11.6',descripcion:'DM tipo 2 con pie diabético',capitulo:'IV'},{codigo:'E13.9',descripcion:'Diabetes mellitus otra especificada',capitulo:'IV'},
  {codigo:'E14.9',descripcion:'Diabetes mellitus no especificada',capitulo:'IV'},{codigo:'E16.2',descripcion:'Hipoglucemia no especificada',capitulo:'IV'},
  {codigo:'E20.9',descripcion:'Hipoparatiroidismo',capitulo:'IV'},{codigo:'E21.0',descripcion:'Hiperparatiroidismo primario',capitulo:'IV'},
  {codigo:'E22.0',descripcion:'Acromegalia y gigantismo',capitulo:'IV'},{codigo:'E23.0',descripcion:'Hipopituitarismo',capitulo:'IV'},
  {codigo:'E24.9',descripcion:'Síndrome de Cushing',capitulo:'IV'},{codigo:'E25.0',descripcion:'Hiperplasia suprarrenal congénita',capitulo:'IV'},
  {codigo:'E27.1',descripcion:'Insuficiencia suprarrenal primaria (Addison)',capitulo:'IV'},{codigo:'E27.4',descripcion:'Insuficiencia suprarrenal no especificada',capitulo:'IV'},
  {codigo:'E28.2',descripcion:'Síndrome de ovario poliquístico',capitulo:'IV'},{codigo:'E34.9',descripcion:'Trastorno endocrino no especificado',capitulo:'IV'},
  {codigo:'E44.1',descripcion:'Desnutrición proteico-calórica leve',capitulo:'IV'},{codigo:'E46',descripcion:'Desnutrición proteico-calórica no especificada',capitulo:'IV'},
  {codigo:'E55.9',descripcion:'Deficiencia de vitamina D',capitulo:'IV'},{codigo:'E61.1',descripcion:'Deficiencia de hierro',capitulo:'IV'},
  {codigo:'E63.9',descripcion:'Deficiencia nutricional no especificada',capitulo:'IV'},{codigo:'E66.0',descripcion:'Obesidad por exceso de calorías',capitulo:'IV'},
  {codigo:'E66.9',descripcion:'Obesidad no especificada',capitulo:'IV'},{codigo:'E78.0',descripcion:'Hipercolesterolemia pura',capitulo:'IV'},
  {codigo:'E78.1',descripcion:'Hipertrigliceridemia pura',capitulo:'IV'},{codigo:'E78.2',descripcion:'Hiperlipidemia mixta',capitulo:'IV'},
  {codigo:'E78.5',descripcion:'Hiperlipidemia no especificada',capitulo:'IV'},{codigo:'E79.0',descripcion:'Hiperuricemia',capitulo:'IV'},
  {codigo:'E83.5',descripcion:'Trastornos del metabolismo del calcio',capitulo:'IV'},{codigo:'E86',descripcion:'Deshidratación',capitulo:'IV'},
  {codigo:'E87.1',descripcion:'Hiponatremia',capitulo:'IV'},{codigo:'E87.5',descripcion:'Hiperpotasemia',capitulo:'IV'},
  {codigo:'E87.6',descripcion:'Hipopotasemia',capitulo:'IV'},{codigo:'E88.9',descripcion:'Trastorno metabólico no especificado',capitulo:'IV'},

  // ═══ Cap V: F00-F99 Trastornos mentales ═══
  {codigo:'F00.9',descripcion:'Demencia en enfermedad de Alzheimer',capitulo:'V'},{codigo:'F01.9',descripcion:'Demencia vascular',capitulo:'V'},
  {codigo:'F03',descripcion:'Demencia no especificada',capitulo:'V'},{codigo:'F05.9',descripcion:'Delirium no especificado',capitulo:'V'},
  {codigo:'F10.2',descripcion:'Dependencia al alcohol',capitulo:'V'},{codigo:'F10.3',descripcion:'Síndrome de abstinencia alcohólica',capitulo:'V'},
  {codigo:'F12.2',descripcion:'Dependencia a cannabis',capitulo:'V'},{codigo:'F14.2',descripcion:'Dependencia a cocaína',capitulo:'V'},
  {codigo:'F17.2',descripcion:'Dependencia al tabaco',capitulo:'V'},{codigo:'F19.9',descripcion:'Trastorno por uso de sustancias',capitulo:'V'},
  {codigo:'F20.0',descripcion:'Esquizofrenia paranoide',capitulo:'V'},{codigo:'F20.9',descripcion:'Esquizofrenia no especificada',capitulo:'V'},
  {codigo:'F25.9',descripcion:'Trastorno esquizoafectivo',capitulo:'V'},{codigo:'F31.9',descripcion:'Trastorno afectivo bipolar',capitulo:'V'},
  {codigo:'F32.0',descripcion:'Episodio depresivo leve',capitulo:'V'},{codigo:'F32.1',descripcion:'Episodio depresivo moderado',capitulo:'V'},
  {codigo:'F32.2',descripcion:'Episodio depresivo grave sin psicosis',capitulo:'V'},{codigo:'F32.9',descripcion:'Episodio depresivo no especificado',capitulo:'V'},
  {codigo:'F33.9',descripcion:'Trastorno depresivo recurrente',capitulo:'V'},{codigo:'F34.1',descripcion:'Distimia',capitulo:'V'},
  {codigo:'F40.1',descripcion:'Fobias sociales',capitulo:'V'},{codigo:'F41.0',descripcion:'Trastorno de pánico',capitulo:'V'},
  {codigo:'F41.1',descripcion:'Trastorno de ansiedad generalizada',capitulo:'V'},{codigo:'F41.2',descripcion:'Trastorno mixto ansioso-depresivo',capitulo:'V'},
  {codigo:'F41.9',descripcion:'Trastorno de ansiedad no especificado',capitulo:'V'},{codigo:'F42',descripcion:'Trastorno obsesivo-compulsivo',capitulo:'V'},
  {codigo:'F43.0',descripcion:'Reacción a estrés agudo',capitulo:'V'},{codigo:'F43.1',descripcion:'Trastorno de estrés postraumático',capitulo:'V'},
  {codigo:'F43.2',descripcion:'Trastorno de adaptación',capitulo:'V'},{codigo:'F45.9',descripcion:'Trastorno somatomorfo',capitulo:'V'},
  {codigo:'F50.0',descripcion:'Anorexia nerviosa',capitulo:'V'},{codigo:'F50.2',descripcion:'Bulimia nerviosa',capitulo:'V'},
  {codigo:'F51.0',descripcion:'Insomnio no orgánico',capitulo:'V'},{codigo:'F60.3',descripcion:'Trastorno de personalidad limítrofe',capitulo:'V'},
  {codigo:'F70',descripcion:'Discapacidad intelectual leve',capitulo:'V'},{codigo:'F84.0',descripcion:'Autismo infantil',capitulo:'V'},
  {codigo:'F90.0',descripcion:'TDAH',capitulo:'V'},{codigo:'F91.9',descripcion:'Trastorno de conducta',capitulo:'V'},
  {codigo:'F99',descripcion:'Trastorno mental no especificado',capitulo:'V'},

  // ═══ Cap VI: G00-G99 Enfermedades del sistema nervioso ═══
  {codigo:'G00.9',descripcion:'Meningitis bacteriana no especificada',capitulo:'VI'},{codigo:'G03.9',descripcion:'Meningitis no especificada',capitulo:'VI'},
  {codigo:'G04.9',descripcion:'Encefalitis no especificada',capitulo:'VI'},{codigo:'G06.0',descripcion:'Absceso intracraneal',capitulo:'VI'},
  {codigo:'G20',descripcion:'Enfermedad de Parkinson',capitulo:'VI'},{codigo:'G25.0',descripcion:'Temblor esencial',capitulo:'VI'},
  {codigo:'G30.9',descripcion:'Enfermedad de Alzheimer',capitulo:'VI'},{codigo:'G35',descripcion:'Esclerosis múltiple',capitulo:'VI'},
  {codigo:'G40.9',descripcion:'Epilepsia no especificada',capitulo:'VI'},{codigo:'G43.9',descripcion:'Migraña no especificada',capitulo:'VI'},
  {codigo:'G44.2',descripcion:'Cefalea tensional',capitulo:'VI'},{codigo:'G45.9',descripcion:'Accidente isquémico transitorio',capitulo:'VI'},
  {codigo:'G47.0',descripcion:'Insomnio',capitulo:'VI'},{codigo:'G47.3',descripcion:'Apnea del sueño',capitulo:'VI'},
  {codigo:'G50.0',descripcion:'Neuralgia del trigémino',capitulo:'VI'},{codigo:'G51.0',descripcion:'Parálisis de Bell',capitulo:'VI'},
  {codigo:'G54.1',descripcion:'Radiculopatía lumbosacra',capitulo:'VI'},{codigo:'G56.0',descripcion:'Síndrome del túnel carpiano',capitulo:'VI'},
  {codigo:'G61.0',descripcion:'Síndrome de Guillain-Barré',capitulo:'VI'},{codigo:'G62.9',descripcion:'Polineuropatía no especificada',capitulo:'VI'},
  {codigo:'G70.0',descripcion:'Miastenia gravis',capitulo:'VI'},{codigo:'G80.9',descripcion:'Parálisis cerebral infantil',capitulo:'VI'},
  {codigo:'G93.4',descripcion:'Encefalopatía no especificada',capitulo:'VI'},

  // ═══ Cap VII: H00-H59 Enfermedades del ojo ═══
  {codigo:'H00.0',descripcion:'Orzuelo',capitulo:'VII'},{codigo:'H01.0',descripcion:'Blefaritis',capitulo:'VII'},
  {codigo:'H04.1',descripcion:'Ojo seco (queratoconjuntivitis seca)',capitulo:'VII'},{codigo:'H10.9',descripcion:'Conjuntivitis no especificada',capitulo:'VII'},
  {codigo:'H10.1',descripcion:'Conjuntivitis alérgica aguda',capitulo:'VII'},{codigo:'H16.9',descripcion:'Queratitis no especificada',capitulo:'VII'},
  {codigo:'H18.6',descripcion:'Queratocono',capitulo:'VII'},{codigo:'H20.9',descripcion:'Iridociclitis no especificada',capitulo:'VII'},
  {codigo:'H25.9',descripcion:'Catarata senil no especificada',capitulo:'VII'},{codigo:'H26.9',descripcion:'Catarata no especificada',capitulo:'VII'},
  {codigo:'H33.0',descripcion:'Desprendimiento de retina',capitulo:'VII'},{codigo:'H35.3',descripcion:'Degeneración macular',capitulo:'VII'},
  {codigo:'H36.0',descripcion:'Retinopatía diabética',capitulo:'VII'},{codigo:'H40.1',descripcion:'Glaucoma primario ángulo abierto',capitulo:'VII'},
  {codigo:'H40.9',descripcion:'Glaucoma no especificado',capitulo:'VII'},{codigo:'H43.3',descripcion:'Opacidades del vítreo',capitulo:'VII'},
  {codigo:'H46',descripcion:'Neuritis óptica',capitulo:'VII'},{codigo:'H49.9',descripcion:'Estrabismo paralítico',capitulo:'VII'},
  {codigo:'H52.1',descripcion:'Miopía',capitulo:'VII'},{codigo:'H52.0',descripcion:'Hipermetropía',capitulo:'VII'},
  {codigo:'H52.2',descripcion:'Astigmatismo',capitulo:'VII'},{codigo:'H52.4',descripcion:'Presbicia',capitulo:'VII'},
  {codigo:'H53.9',descripcion:'Perturbación visual no especificada',capitulo:'VII'},{codigo:'H54.9',descripcion:'Discapacidad visual no especificada',capitulo:'VII'},

  // ═══ Cap VIII: H60-H95 Enfermedades del oído ═══
  {codigo:'H60.9',descripcion:'Otitis externa no especificada',capitulo:'VIII'},{codigo:'H61.2',descripcion:'Cerumen impactado',capitulo:'VIII'},
  {codigo:'H65.9',descripcion:'Otitis media no supurativa',capitulo:'VIII'},{codigo:'H66.9',descripcion:'Otitis media supurativa',capitulo:'VIII'},
  {codigo:'H68.1',descripcion:'Disfunción de trompa de Eustaquio',capitulo:'VIII'},{codigo:'H70.0',descripcion:'Mastoiditis aguda',capitulo:'VIII'},
  {codigo:'H72.9',descripcion:'Perforación timpánica',capitulo:'VIII'},{codigo:'H81.0',descripcion:'Enfermedad de Ménière',capitulo:'VIII'},
  {codigo:'H81.1',descripcion:'Vértigo paroxístico benigno',capitulo:'VIII'},{codigo:'H81.9',descripcion:'Trastorno vestibular no especificado',capitulo:'VIII'},
  {codigo:'H83.0',descripcion:'Laberintitis',capitulo:'VIII'},{codigo:'H90.5',descripcion:'Hipoacusia neurosensorial bilateral',capitulo:'VIII'},
  {codigo:'H90.6',descripcion:'Hipoacusia mixta bilateral',capitulo:'VIII'},{codigo:'H91.9',descripcion:'Hipoacusia no especificada',capitulo:'VIII'},
  {codigo:'H93.1',descripcion:'Tinnitus (acúfenos)',capitulo:'VIII'},

  // ═══ Cap IX: I00-I99 Enfermedades del sistema circulatorio ═══
  {codigo:'I00',descripcion:'Fiebre reumática sin mención cardíaca',capitulo:'IX'},{codigo:'I05.1',descripcion:'Insuficiencia mitral reumática',capitulo:'IX'},
  {codigo:'I10',descripcion:'Hipertensión arterial esencial',capitulo:'IX'},{codigo:'I11.9',descripcion:'Cardiopatía hipertensiva sin ICC',capitulo:'IX'},
  {codigo:'I13.9',descripcion:'Enfermedad cardiorrenal hipertensiva',capitulo:'IX'},{codigo:'I20.0',descripcion:'Angina inestable',capitulo:'IX'},
  {codigo:'I20.9',descripcion:'Angina de pecho no especificada',capitulo:'IX'},{codigo:'I21.9',descripcion:'Infarto agudo de miocardio',capitulo:'IX'},
  {codigo:'I25.1',descripcion:'Cardiopatía isquémica crónica',capitulo:'IX'},{codigo:'I25.9',descripcion:'Cardiopatía isquémica no especificada',capitulo:'IX'},
  {codigo:'I26.9',descripcion:'Embolia pulmonar',capitulo:'IX'},{codigo:'I27.0',descripcion:'Hipertensión pulmonar primaria',capitulo:'IX'},
  {codigo:'I34.0',descripcion:'Insuficiencia mitral no reumática',capitulo:'IX'},{codigo:'I35.0',descripcion:'Estenosis aórtica no reumática',capitulo:'IX'},
  {codigo:'I42.0',descripcion:'Miocardiopatía dilatada',capitulo:'IX'},{codigo:'I42.9',descripcion:'Miocardiopatía no especificada',capitulo:'IX'},
  {codigo:'I44.1',descripcion:'Bloqueo AV de segundo grado',capitulo:'IX'},{codigo:'I44.2',descripcion:'Bloqueo AV completo',capitulo:'IX'},
  {codigo:'I47.1',descripcion:'Taquicardia supraventricular',capitulo:'IX'},{codigo:'I47.2',descripcion:'Taquicardia ventricular',capitulo:'IX'},
  {codigo:'I48',descripcion:'Fibrilación y flutter auricular',capitulo:'IX'},{codigo:'I49.9',descripcion:'Arritmia cardíaca no especificada',capitulo:'IX'},
  {codigo:'I50.0',descripcion:'Insuficiencia cardíaca congestiva',capitulo:'IX'},{codigo:'I50.9',descripcion:'Insuficiencia cardíaca no especificada',capitulo:'IX'},
  {codigo:'I60.9',descripcion:'Hemorragia subaracnoidea',capitulo:'IX'},{codigo:'I61.9',descripcion:'Hemorragia intracerebral',capitulo:'IX'},
  {codigo:'I63.9',descripcion:'Infarto cerebral (EVC isquémico)',capitulo:'IX'},{codigo:'I64',descripcion:'EVC no especificado',capitulo:'IX'},
  {codigo:'I67.9',descripcion:'Enfermedad cerebrovascular no especificada',capitulo:'IX'},{codigo:'I70.0',descripcion:'Aterosclerosis de la aorta',capitulo:'IX'},
  {codigo:'I70.2',descripcion:'Aterosclerosis de arterias de extremidades',capitulo:'IX'},{codigo:'I73.9',descripcion:'Enfermedad vascular periférica',capitulo:'IX'},
  {codigo:'I80.2',descripcion:'Trombosis venosa profunda de MMII',capitulo:'IX'},{codigo:'I83.9',descripcion:'Venas varicosas de miembros inferiores',capitulo:'IX'},
  {codigo:'I84.9',descripcion:'Hemorroides',capitulo:'IX'},{codigo:'I87.2',descripcion:'Insuficiencia venosa crónica',capitulo:'IX'},
  {codigo:'I95.1',descripcion:'Hipotensión ortostática',capitulo:'IX'},{codigo:'I99',descripcion:'Trastorno del sistema circulatorio no especificado',capitulo:'IX'},

  // ═══ Cap X: J00-J99 Enfermedades del sistema respiratorio ═══
  {codigo:'J00',descripcion:'Rinofaringitis aguda (resfriado común)',capitulo:'X'},{codigo:'J01.9',descripcion:'Sinusitis aguda no especificada',capitulo:'X'},
  {codigo:'J02.9',descripcion:'Faringitis aguda no especificada',capitulo:'X'},{codigo:'J03.9',descripcion:'Amigdalitis aguda no especificada',capitulo:'X'},
  {codigo:'J04.0',descripcion:'Laringitis aguda',capitulo:'X'},{codigo:'J05.0',descripcion:'Laringotraqueitis obstructiva aguda (crup)',capitulo:'X'},
  {codigo:'J06.9',descripcion:'IVRS aguda no especificada',capitulo:'X'},{codigo:'J10.1',descripcion:'Influenza con otras manifestaciones respiratorias',capitulo:'X'},
  {codigo:'J11.1',descripcion:'Influenza no especificada',capitulo:'X'},{codigo:'J12.9',descripcion:'Neumonía viral no especificada',capitulo:'X'},
  {codigo:'J13',descripcion:'Neumonía por Streptococcus pneumoniae',capitulo:'X'},{codigo:'J15.9',descripcion:'Neumonía bacteriana no especificada',capitulo:'X'},
  {codigo:'J18.0',descripcion:'Bronconeumonía no especificada',capitulo:'X'},{codigo:'J18.9',descripcion:'Neumonía no especificada',capitulo:'X'},
  {codigo:'J20.9',descripcion:'Bronquitis aguda no especificada',capitulo:'X'},{codigo:'J21.9',descripcion:'Bronquiolitis aguda',capitulo:'X'},
  {codigo:'J22',descripcion:'IVRI aguda no especificada',capitulo:'X'},{codigo:'J30.1',descripcion:'Rinitis alérgica por polen',capitulo:'X'},
  {codigo:'J30.4',descripcion:'Rinitis alérgica no especificada',capitulo:'X'},{codigo:'J31.0',descripcion:'Rinitis crónica',capitulo:'X'},
  {codigo:'J32.9',descripcion:'Sinusitis crónica no especificada',capitulo:'X'},{codigo:'J34.2',descripcion:'Desviación del tabique nasal',capitulo:'X'},
  {codigo:'J35.0',descripcion:'Amigdalitis crónica',capitulo:'X'},{codigo:'J35.1',descripcion:'Hipertrofia de adenoides',capitulo:'X'},
  {codigo:'J37.0',descripcion:'Laringitis crónica',capitulo:'X'},{codigo:'J38.0',descripcion:'Parálisis de cuerdas vocales',capitulo:'X'},
  {codigo:'J42',descripcion:'Bronquitis crónica no especificada',capitulo:'X'},{codigo:'J43.9',descripcion:'Enfisema',capitulo:'X'},
  {codigo:'J44.1',descripcion:'EPOC con exacerbación aguda',capitulo:'X'},{codigo:'J44.9',descripcion:'EPOC no especificada',capitulo:'X'},
  {codigo:'J45.9',descripcion:'Asma no especificada',capitulo:'X'},{codigo:'J45.0',descripcion:'Asma predominantemente alérgica',capitulo:'X'},
  {codigo:'J46',descripcion:'Estado asmático (asma aguda grave)',capitulo:'X'},{codigo:'J47',descripcion:'Bronquiectasia',capitulo:'X'},
  {codigo:'J80',descripcion:'Síndrome de dificultad respiratoria aguda (SDRA)',capitulo:'X'},{codigo:'J84.1',descripcion:'Fibrosis pulmonar idiopática',capitulo:'X'},
  {codigo:'J90',descripcion:'Derrame pleural',capitulo:'X'},{codigo:'J93.9',descripcion:'Neumotórax',capitulo:'X'},
  {codigo:'J96.0',descripcion:'Insuficiencia respiratoria aguda',capitulo:'X'},{codigo:'J96.9',descripcion:'Insuficiencia respiratoria no especificada',capitulo:'X'},
  {codigo:'J98.4',descripcion:'Otros trastornos pulmonares',capitulo:'X'},

  // ═══ Cap XI: K00-K93 Enfermedades del aparato digestivo ═══
  {codigo:'K00.6',descripcion:'Trastornos de la erupción dentaria',capitulo:'XI'},{codigo:'K02.9',descripcion:'Caries dental',capitulo:'XI'},
  {codigo:'K04.0',descripcion:'Pulpitis',capitulo:'XI'},{codigo:'K04.7',descripcion:'Absceso periapical',capitulo:'XI'},
  {codigo:'K05.1',descripcion:'Gingivitis crónica',capitulo:'XI'},{codigo:'K05.3',descripcion:'Periodontitis crónica',capitulo:'XI'},
  {codigo:'K08.1',descripcion:'Pérdida de dientes',capitulo:'XI'},{codigo:'K12.0',descripcion:'Estomatitis aftosa recurrente',capitulo:'XI'},
  {codigo:'K13.7',descripcion:'Lesiones de la mucosa oral',capitulo:'XI'},{codigo:'K20',descripcion:'Esofagitis',capitulo:'XI'},
  {codigo:'K21.0',descripcion:'ERGE con esofagitis',capitulo:'XI'},{codigo:'K21.9',descripcion:'ERGE sin esofagitis',capitulo:'XI'},
  {codigo:'K25.9',descripcion:'Úlcera gástrica',capitulo:'XI'},{codigo:'K26.9',descripcion:'Úlcera duodenal',capitulo:'XI'},
  {codigo:'K27.9',descripcion:'Úlcera péptica no especificada',capitulo:'XI'},{codigo:'K29.1',descripcion:'Gastritis aguda',capitulo:'XI'},
  {codigo:'K29.5',descripcion:'Gastritis crónica',capitulo:'XI'},{codigo:'K29.7',descripcion:'Gastritis no especificada',capitulo:'XI'},
  {codigo:'K30',descripcion:'Dispepsia funcional',capitulo:'XI'},{codigo:'K35.8',descripcion:'Apendicitis aguda',capitulo:'XI'},
  {codigo:'K37',descripcion:'Apendicitis no especificada',capitulo:'XI'},{codigo:'K40.9',descripcion:'Hernia inguinal unilateral',capitulo:'XI'},
  {codigo:'K41.9',descripcion:'Hernia femoral',capitulo:'XI'},{codigo:'K42.9',descripcion:'Hernia umbilical',capitulo:'XI'},
  {codigo:'K43.9',descripcion:'Hernia ventral',capitulo:'XI'},{codigo:'K44.9',descripcion:'Hernia hiatal',capitulo:'XI'},
  {codigo:'K50.9',descripcion:'Enfermedad de Crohn',capitulo:'XI'},{codigo:'K51.9',descripcion:'Colitis ulcerativa',capitulo:'XI'},
  {codigo:'K52.9',descripcion:'Colitis no infecciosa no especificada',capitulo:'XI'},{codigo:'K56.6',descripcion:'Obstrucción intestinal',capitulo:'XI'},
  {codigo:'K57.3',descripcion:'Enfermedad diverticular del intestino grueso',capitulo:'XI'},{codigo:'K58.9',descripcion:'Síndrome de intestino irritable',capitulo:'XI'},
  {codigo:'K59.0',descripcion:'Estreñimiento',capitulo:'XI'},{codigo:'K60.0',descripcion:'Fisura anal aguda',capitulo:'XI'},
  {codigo:'K61.0',descripcion:'Absceso anal',capitulo:'XI'},{codigo:'K62.5',descripcion:'Hemorragia del ano y recto',capitulo:'XI'},
  {codigo:'K65.0',descripcion:'Peritonitis aguda',capitulo:'XI'},{codigo:'K70.3',descripcion:'Cirrosis hepática alcohólica',capitulo:'XI'},
  {codigo:'K72.9',descripcion:'Insuficiencia hepática no especificada',capitulo:'XI'},{codigo:'K74.6',descripcion:'Cirrosis hepática no especificada',capitulo:'XI'},
  {codigo:'K75.9',descripcion:'Hepatitis inflamatoria no especificada',capitulo:'XI'},{codigo:'K76.0',descripcion:'Hígado graso (esteatosis hepática)',capitulo:'XI'},
  {codigo:'K80.2',descripcion:'Colelitiasis sin colecistitis',capitulo:'XI'},{codigo:'K81.0',descripcion:'Colecistitis aguda',capitulo:'XI'},
  {codigo:'K85.9',descripcion:'Pancreatitis aguda',capitulo:'XI'},{codigo:'K86.1',descripcion:'Pancreatitis crónica',capitulo:'XI'},
  {codigo:'K92.2',descripcion:'Hemorragia gastrointestinal no especificada',capitulo:'XI'},

  // ═══ Cap XII: L00-L99 Enfermedades de la piel ═══
  {codigo:'L00',descripcion:'Síndrome estafilocócico de piel escaldada',capitulo:'XII'},{codigo:'L01.0',descripcion:'Impétigo',capitulo:'XII'},
  {codigo:'L02.9',descripcion:'Absceso cutáneo / furúnculo',capitulo:'XII'},{codigo:'L03.9',descripcion:'Celulitis',capitulo:'XII'},
  {codigo:'L04.9',descripcion:'Linfadenitis aguda',capitulo:'XII'},{codigo:'L08.9',descripcion:'Infección local de piel no especificada',capitulo:'XII'},
  {codigo:'L20.9',descripcion:'Dermatitis atópica',capitulo:'XII'},{codigo:'L21.0',descripcion:'Dermatitis seborreica del cuero cabelludo',capitulo:'XII'},
  {codigo:'L23.9',descripcion:'Dermatitis alérgica de contacto',capitulo:'XII'},{codigo:'L24.9',descripcion:'Dermatitis irritativa de contacto',capitulo:'XII'},
  {codigo:'L25.9',descripcion:'Dermatitis de contacto no especificada',capitulo:'XII'},{codigo:'L27.0',descripcion:'Erupción cutánea por fármacos',capitulo:'XII'},
  {codigo:'L29.9',descripcion:'Prurito no especificado',capitulo:'XII'},{codigo:'L30.9',descripcion:'Dermatitis no especificada',capitulo:'XII'},
  {codigo:'L40.0',descripcion:'Psoriasis vulgar',capitulo:'XII'},{codigo:'L40.9',descripcion:'Psoriasis no especificada',capitulo:'XII'},
  {codigo:'L42',descripcion:'Pitiriasis rosada',capitulo:'XII'},{codigo:'L50.0',descripcion:'Urticaria alérgica',capitulo:'XII'},
  {codigo:'L50.9',descripcion:'Urticaria no especificada',capitulo:'XII'},{codigo:'L51.9',descripcion:'Eritema multiforme',capitulo:'XII'},
  {codigo:'L53.9',descripcion:'Eritema no especificado',capitulo:'XII'},{codigo:'L60.0',descripcion:'Uña encarnada (onicocriptosis)',capitulo:'XII'},
  {codigo:'L63.9',descripcion:'Alopecia areata',capitulo:'XII'},{codigo:'L65.9',descripcion:'Alopecia no cicatrizal',capitulo:'XII'},
  {codigo:'L70.0',descripcion:'Acné vulgar',capitulo:'XII'},{codigo:'L72.0',descripcion:'Quiste epidérmico',capitulo:'XII'},
  {codigo:'L73.9',descripcion:'Foliculitis no especificada',capitulo:'XII'},{codigo:'L80',descripcion:'Vitiligo',capitulo:'XII'},
  {codigo:'L81.1',descripcion:'Cloasma (melasma)',capitulo:'XII'},{codigo:'L82',descripcion:'Queratosis seborreica',capitulo:'XII'},
  {codigo:'L84',descripcion:'Callosidades',capitulo:'XII'},{codigo:'L90.5',descripcion:'Cicatriz/fibrosis de piel',capitulo:'XII'},
  {codigo:'L91.0',descripcion:'Cicatriz queloide',capitulo:'XII'},{codigo:'L97',descripcion:'Úlcera de miembro inferior',capitulo:'XII'},
  {codigo:'L98.9',descripcion:'Trastorno de piel no especificado',capitulo:'XII'},

  // ═══ Cap XIII: M00-M99 Enfermedades del sistema osteomuscular ═══
  {codigo:'M06.9',descripcion:'Artritis reumatoide no especificada',capitulo:'XIII'},{codigo:'M10.9',descripcion:'Gota no especificada',capitulo:'XIII'},
  {codigo:'M13.9',descripcion:'Artritis no especificada',capitulo:'XIII'},{codigo:'M15.9',descripcion:'Poliartrosis',capitulo:'XIII'},
  {codigo:'M16.9',descripcion:'Coxartrosis (artrosis de cadera)',capitulo:'XIII'},{codigo:'M17.9',descripcion:'Gonartrosis (artrosis de rodilla)',capitulo:'XIII'},
  {codigo:'M19.9',descripcion:'Artrosis no especificada',capitulo:'XIII'},{codigo:'M20.1',descripcion:'Hallux valgus (juanete)',capitulo:'XIII'},
  {codigo:'M23.5',descripcion:'Lesión de menisco',capitulo:'XIII'},{codigo:'M25.5',descripcion:'Dolor articular',capitulo:'XIII'},
  {codigo:'M32.9',descripcion:'Lupus eritematoso sistémico',capitulo:'XIII'},{codigo:'M34.9',descripcion:'Esclerosis sistémica (esclerodermia)',capitulo:'XIII'},
  {codigo:'M35.3',descripcion:'Polimialgia reumática',capitulo:'XIII'},{codigo:'M41.9',descripcion:'Escoliosis',capitulo:'XIII'},
  {codigo:'M43.1',descripcion:'Espondilolistesis',capitulo:'XIII'},{codigo:'M45',descripcion:'Espondilitis anquilosante',capitulo:'XIII'},
  {codigo:'M47.8',descripcion:'Espondilosis',capitulo:'XIII'},{codigo:'M48.0',descripcion:'Estenosis espinal',capitulo:'XIII'},
  {codigo:'M50.1',descripcion:'Hernia de disco cervical',capitulo:'XIII'},{codigo:'M51.1',descripcion:'Hernia de disco lumbar con radiculopatía',capitulo:'XIII'},
  {codigo:'M51.2',descripcion:'Degeneración de disco lumbar',capitulo:'XIII'},{codigo:'M54.2',descripcion:'Cervicalgia',capitulo:'XIII'},
  {codigo:'M54.4',descripcion:'Lumbago con ciática',capitulo:'XIII'},{codigo:'M54.5',descripcion:'Lumbago (dolor lumbar bajo)',capitulo:'XIII'},
  {codigo:'M54.9',descripcion:'Dorsalgia no especificada',capitulo:'XIII'},{codigo:'M62.8',descripcion:'Otros trastornos musculares',capitulo:'XIII'},
  {codigo:'M65.9',descripcion:'Sinovitis y tenosinovitis',capitulo:'XIII'},{codigo:'M67.4',descripcion:'Ganglión',capitulo:'XIII'},
  {codigo:'M70.6',descripcion:'Bursitis trocantérica',capitulo:'XIII'},{codigo:'M71.9',descripcion:'Bursitis no especificada',capitulo:'XIII'},
  {codigo:'M72.0',descripcion:'Fibromatosis de la fascia palmar (Dupuytren)',capitulo:'XIII'},{codigo:'M75.1',descripcion:'Síndrome del manguito rotador',capitulo:'XIII'},
  {codigo:'M76.6',descripcion:'Tendinitis aquílea',capitulo:'XIII'},{codigo:'M77.0',descripcion:'Epicondilitis medial',capitulo:'XIII'},
  {codigo:'M77.1',descripcion:'Epicondilitis lateral (codo de tenista)',capitulo:'XIII'},{codigo:'M77.3',descripcion:'Espolón calcáneo',capitulo:'XIII'},
  {codigo:'M79.1',descripcion:'Mialgia',capitulo:'XIII'},{codigo:'M79.3',descripcion:'Paniculitis',capitulo:'XIII'},
  {codigo:'M79.7',descripcion:'Fibromialgia',capitulo:'XIII'},{codigo:'M80.9',descripcion:'Osteoporosis con fractura patológica',capitulo:'XIII'},
  {codigo:'M81.9',descripcion:'Osteoporosis sin fractura',capitulo:'XIII'},

  // ═══ Cap XIV: N00-N99 Enfermedades del aparato genitourinario ═══
  {codigo:'N00.9',descripcion:'Síndrome nefrítico agudo',capitulo:'XIV'},{codigo:'N03.9',descripcion:'Síndrome nefrítico crónico',capitulo:'XIV'},
  {codigo:'N04.9',descripcion:'Síndrome nefrótico',capitulo:'XIV'},{codigo:'N10',descripcion:'Nefritis tubulointersticial aguda (pielonefritis)',capitulo:'XIV'},
  {codigo:'N11.9',descripcion:'Nefritis tubulointersticial crónica',capitulo:'XIV'},{codigo:'N12',descripcion:'Nefritis tubulointersticial no especificada',capitulo:'XIV'},
  {codigo:'N17.9',descripcion:'Insuficiencia renal aguda',capitulo:'XIV'},{codigo:'N18.9',descripcion:'Enfermedad renal crónica',capitulo:'XIV'},
  {codigo:'N19',descripcion:'Insuficiencia renal no especificada',capitulo:'XIV'},{codigo:'N20.0',descripcion:'Cálculo del riñón (litiasis renal)',capitulo:'XIV'},
  {codigo:'N20.1',descripcion:'Cálculo del uréter',capitulo:'XIV'},{codigo:'N21.0',descripcion:'Cálculo vesical',capitulo:'XIV'},
  {codigo:'N23',descripcion:'Cólico renal no especificado',capitulo:'XIV'},{codigo:'N28.9',descripcion:'Trastorno renal no especificado',capitulo:'XIV'},
  {codigo:'N30.0',descripcion:'Cistitis aguda',capitulo:'XIV'},{codigo:'N30.9',descripcion:'Cistitis no especificada',capitulo:'XIV'},
  {codigo:'N34.1',descripcion:'Uretritis no especificada',capitulo:'XIV'},{codigo:'N39.0',descripcion:'Infección de vías urinarias',capitulo:'XIV'},
  {codigo:'N39.4',descripcion:'Incontinencia urinaria',capitulo:'XIV'},{codigo:'N40',descripcion:'Hiperplasia prostática benigna',capitulo:'XIV'},
  {codigo:'N41.0',descripcion:'Prostatitis aguda',capitulo:'XIV'},{codigo:'N41.1',descripcion:'Prostatitis crónica',capitulo:'XIV'},
  {codigo:'N43.3',descripcion:'Hidrocele no especificado',capitulo:'XIV'},{codigo:'N44',descripcion:'Torsión testicular',capitulo:'XIV'},
  {codigo:'N45.9',descripcion:'Orquitis y epididimitis',capitulo:'XIV'},{codigo:'N47',descripcion:'Fimosis',capitulo:'XIV'},
  {codigo:'N48.1',descripcion:'Balanitis',capitulo:'XIV'},{codigo:'N60.1',descripcion:'Mastopatía quística difusa',capitulo:'XIV'},
  {codigo:'N61',descripcion:'Mastitis',capitulo:'XIV'},{codigo:'N63',descripcion:'Nódulo mamario no especificado',capitulo:'XIV'},
  {codigo:'N70.9',descripcion:'Salpingitis y ooforitis',capitulo:'XIV'},{codigo:'N71.9',descripcion:'Endometritis',capitulo:'XIV'},
  {codigo:'N72',descripcion:'Cervicitis',capitulo:'XIV'},{codigo:'N73.0',descripcion:'Enfermedad pélvica inflamatoria aguda',capitulo:'XIV'},
  {codigo:'N76.0',descripcion:'Vaginitis aguda',capitulo:'XIV'},{codigo:'N77.1',descripcion:'Vaginitis en enfermedades infecciosas',capitulo:'XIV'},
  {codigo:'N80.9',descripcion:'Endometriosis no especificada',capitulo:'XIV'},{codigo:'N83.2',descripcion:'Quiste ovárico',capitulo:'XIV'},
  {codigo:'N84.0',descripcion:'Pólipo endometrial',capitulo:'XIV'},{codigo:'N85.0',descripcion:'Hiperplasia endometrial',capitulo:'XIV'},
  {codigo:'N91.2',descripcion:'Amenorrea no especificada',capitulo:'XIV'},{codigo:'N92.0',descripcion:'Menstruación excesiva y frecuente',capitulo:'XIV'},
  {codigo:'N92.6',descripcion:'Menstruación irregular no especificada',capitulo:'XIV'},{codigo:'N94.6',descripcion:'Dismenorrea no especificada',capitulo:'XIV'},
  {codigo:'N95.1',descripcion:'Estados menopáusicos y climatéricos',capitulo:'XIV'},

  // ═══ Cap XV: O00-O99 Embarazo, parto y puerperio ═══
  {codigo:'O00.9',descripcion:'Embarazo ectópico',capitulo:'XV'},{codigo:'O02.1',descripcion:'Aborto retenido',capitulo:'XV'},
  {codigo:'O03.9',descripcion:'Aborto espontáneo completo',capitulo:'XV'},{codigo:'O06.9',descripcion:'Aborto no especificado',capitulo:'XV'},
  {codigo:'O10.0',descripcion:'HTA preexistente en el embarazo',capitulo:'XV'},{codigo:'O13',descripcion:'HTA gestacional sin proteinuria',capitulo:'XV'},
  {codigo:'O14.0',descripcion:'Preeclampsia moderada',capitulo:'XV'},{codigo:'O14.1',descripcion:'Preeclampsia severa',capitulo:'XV'},
  {codigo:'O15.0',descripcion:'Eclampsia en el embarazo',capitulo:'XV'},{codigo:'O20.0',descripcion:'Amenaza de aborto',capitulo:'XV'},
  {codigo:'O21.0',descripcion:'Hiperemesis gravídica leve',capitulo:'XV'},{codigo:'O23.4',descripcion:'Infección urinaria en embarazo',capitulo:'XV'},
  {codigo:'O24.4',descripcion:'Diabetes gestacional',capitulo:'XV'},{codigo:'O26.8',descripcion:'Otras complicaciones del embarazo',capitulo:'XV'},
  {codigo:'O28.9',descripcion:'Hallazgo anormal en examen prenatal',capitulo:'XV'},{codigo:'O32.1',descripcion:'Presentación de nalgas',capitulo:'XV'},
  {codigo:'O34.2',descripcion:'Cicatriz uterina previa por cesárea',capitulo:'XV'},{codigo:'O36.4',descripcion:'Muerte intrauterina',capitulo:'XV'},
  {codigo:'O42.9',descripcion:'Ruptura prematura de membranas',capitulo:'XV'},{codigo:'O46.9',descripcion:'Hemorragia anteparto',capitulo:'XV'},
  {codigo:'O47.0',descripcion:'Amenaza de parto prematuro',capitulo:'XV'},{codigo:'O48',descripcion:'Embarazo prolongado',capitulo:'XV'},
  {codigo:'O60.0',descripcion:'Trabajo de parto prematuro',capitulo:'XV'},{codigo:'O62.2',descripcion:'Trabajo de parto disfuncional',capitulo:'XV'},
  {codigo:'O68.0',descripcion:'Sufrimiento fetal',capitulo:'XV'},{codigo:'O69.0',descripcion:'Prolapso del cordón umbilical',capitulo:'XV'},
  {codigo:'O70.1',descripcion:'Desgarro perineal segundo grado',capitulo:'XV'},{codigo:'O72.1',descripcion:'Hemorragia postparto',capitulo:'XV'},
  {codigo:'O80',descripcion:'Parto único espontáneo',capitulo:'XV'},{codigo:'O82',descripcion:'Parto por cesárea',capitulo:'XV'},
  {codigo:'O85',descripcion:'Sepsis puerperal',capitulo:'XV'},{codigo:'O86.0',descripcion:'Infección de herida quirúrgica obstétrica',capitulo:'XV'},
  {codigo:'O90.9',descripcion:'Complicación del puerperio no especificada',capitulo:'XV'},{codigo:'O99.0',descripcion:'Anemia en el embarazo',capitulo:'XV'},

  // ═══ Cap XVI: P00-P96 Afecciones del periodo perinatal ═══
  {codigo:'P05.9',descripcion:'Retardo del crecimiento fetal',capitulo:'XVI'},{codigo:'P07.1',descripcion:'Bajo peso al nacer (1500-2499g)',capitulo:'XVI'},
  {codigo:'P07.3',descripcion:'Prematuridad',capitulo:'XVI'},{codigo:'P08.0',descripcion:'Recién nacido excepcionalmente grande',capitulo:'XVI'},
  {codigo:'P21.0',descripcion:'Asfixia del nacimiento severa',capitulo:'XVI'},{codigo:'P22.0',descripcion:'SDR del recién nacido',capitulo:'XVI'},
  {codigo:'P22.1',descripcion:'Taquipnea transitoria del recién nacido',capitulo:'XVI'},{codigo:'P23.9',descripcion:'Neumonía congénita',capitulo:'XVI'},
  {codigo:'P28.5',descripcion:'Insuficiencia respiratoria del recién nacido',capitulo:'XVI'},{codigo:'P36.9',descripcion:'Sepsis bacteriana del recién nacido',capitulo:'XVI'},
  {codigo:'P38',descripcion:'Onfalitis del recién nacido',capitulo:'XVI'},{codigo:'P39.1',descripcion:'Conjuntivitis neonatal',capitulo:'XVI'},
  {codigo:'P55.1',descripcion:'Incompatibilidad ABO del feto/recién nacido',capitulo:'XVI'},{codigo:'P59.9',descripcion:'Ictericia neonatal no especificada',capitulo:'XVI'},
  {codigo:'P61.0',descripcion:'Trombocitopenia neonatal transitoria',capitulo:'XVI'},{codigo:'P70.4',descripcion:'Hipoglucemia neonatal',capitulo:'XVI'},
  {codigo:'P83.1',descripcion:'Eritema tóxico neonatal',capitulo:'XVI'},{codigo:'P96.9',descripcion:'Condición perinatal no especificada',capitulo:'XVI'},

  // ═══ Cap XVII: Q00-Q99 Malformaciones congénitas ═══
  {codigo:'Q00.0',descripcion:'Anencefalia',capitulo:'XVII'},{codigo:'Q01.9',descripcion:'Encefalocele',capitulo:'XVII'},
  {codigo:'Q03.9',descripcion:'Hidrocefalia congénita',capitulo:'XVII'},{codigo:'Q05.9',descripcion:'Espina bífida',capitulo:'XVII'},
  {codigo:'Q10.5',descripcion:'Estenosis del conducto lagrimal congénita',capitulo:'XVII'},{codigo:'Q17.2',descripcion:'Microtia',capitulo:'XVII'},
  {codigo:'Q20.0',descripcion:'Tronco arterioso común',capitulo:'XVII'},{codigo:'Q21.0',descripcion:'Comunicación interventricular',capitulo:'XVII'},
  {codigo:'Q21.1',descripcion:'Comunicación interauricular',capitulo:'XVII'},{codigo:'Q23.0',descripcion:'Estenosis aórtica congénita',capitulo:'XVII'},
  {codigo:'Q25.0',descripcion:'Conducto arterioso persistente',capitulo:'XVII'},{codigo:'Q25.1',descripcion:'Coartación de la aorta',capitulo:'XVII'},
  {codigo:'Q35.9',descripcion:'Fisura del paladar',capitulo:'XVII'},{codigo:'Q36.9',descripcion:'Labio leporino',capitulo:'XVII'},
  {codigo:'Q39.0',descripcion:'Atresia de esófago',capitulo:'XVII'},{codigo:'Q40.0',descripcion:'Estenosis pilórica congénita',capitulo:'XVII'},
  {codigo:'Q43.1',descripcion:'Enfermedad de Hirschsprung',capitulo:'XVII'},{codigo:'Q53.9',descripcion:'Criptorquidia',capitulo:'XVII'},
  {codigo:'Q54.9',descripcion:'Hipospadias',capitulo:'XVII'},{codigo:'Q62.0',descripcion:'Hidronefrosis congénita',capitulo:'XVII'},
  {codigo:'Q65.9',descripcion:'Displasia congénita de cadera',capitulo:'XVII'},{codigo:'Q66.0',descripcion:'Pie equinovaro',capitulo:'XVII'},
  {codigo:'Q66.7',descripcion:'Pie cavo',capitulo:'XVII'},{codigo:'Q69.9',descripcion:'Polidactilia',capitulo:'XVII'},
  {codigo:'Q79.0',descripcion:'Hernia diafragmática congénita',capitulo:'XVII'},{codigo:'Q90.9',descripcion:'Síndrome de Down',capitulo:'XVII'},

  // ═══ Cap XVIII: R00-R99 Síntomas y signos ═══
  {codigo:'R00.0',descripcion:'Taquicardia no especificada',capitulo:'XVIII'},{codigo:'R00.1',descripcion:'Bradicardia no especificada',capitulo:'XVIII'},
  {codigo:'R00.2',descripcion:'Palpitaciones',capitulo:'XVIII'},{codigo:'R03.0',descripcion:'Lectura elevada de presión arterial',capitulo:'XVIII'},
  {codigo:'R04.0',descripcion:'Epistaxis',capitulo:'XVIII'},{codigo:'R04.2',descripcion:'Hemoptisis',capitulo:'XVIII'},
  {codigo:'R05',descripcion:'Tos',capitulo:'XVIII'},{codigo:'R06.0',descripcion:'Disnea',capitulo:'XVIII'},
  {codigo:'R07.4',descripcion:'Dolor torácico no especificado',capitulo:'XVIII'},{codigo:'R09.8',descripcion:'Otros síntomas del sistema circulatorio/respiratorio',capitulo:'XVIII'},
  {codigo:'R10.1',descripcion:'Dolor abdominal en epigastrio',capitulo:'XVIII'},{codigo:'R10.3',descripcion:'Dolor abdominal bajo',capitulo:'XVIII'},
  {codigo:'R10.4',descripcion:'Dolor abdominal no especificado',capitulo:'XVIII'},{codigo:'R11',descripcion:'Náusea y vómito',capitulo:'XVIII'},
  {codigo:'R12',descripcion:'Pirosis (agruras)',capitulo:'XVIII'},{codigo:'R13.1',descripcion:'Disfagia',capitulo:'XVIII'},
  {codigo:'R14',descripcion:'Flatulencia y distensión abdominal',capitulo:'XVIII'},{codigo:'R17',descripcion:'Ictericia no especificada',capitulo:'XVIII'},
  {codigo:'R19.7',descripcion:'Diarrea no especificada',capitulo:'XVIII'},{codigo:'R20.2',descripcion:'Parestesia de la piel',capitulo:'XVIII'},
  {codigo:'R22.9',descripcion:'Tumefacción localizada no especificada',capitulo:'XVIII'},{codigo:'R25.1',descripcion:'Temblor no especificado',capitulo:'XVIII'},
  {codigo:'R25.2',descripcion:'Calambres y espasmos',capitulo:'XVIII'},{codigo:'R26.8',descripcion:'Alteración de la marcha',capitulo:'XVIII'},
  {codigo:'R27.0',descripcion:'Ataxia no especificada',capitulo:'XVIII'},{codigo:'R30.0',descripcion:'Disuria',capitulo:'XVIII'},
  {codigo:'R31',descripcion:'Hematuria no especificada',capitulo:'XVIII'},{codigo:'R32',descripcion:'Incontinencia urinaria no especificada',capitulo:'XVIII'},
  {codigo:'R33',descripcion:'Retención urinaria',capitulo:'XVIII'},{codigo:'R35',descripcion:'Poliuria',capitulo:'XVIII'},
  {codigo:'R40.0',descripcion:'Somnolencia',capitulo:'XVIII'},{codigo:'R40.2',descripcion:'Coma no especificado',capitulo:'XVIII'},
  {codigo:'R41.0',descripcion:'Desorientación no especificada',capitulo:'XVIII'},{codigo:'R42',descripcion:'Mareo y desvanecimiento',capitulo:'XVIII'},
  {codigo:'R47.0',descripcion:'Disfasia y afasia',capitulo:'XVIII'},{codigo:'R50.9',descripcion:'Fiebre no especificada',capitulo:'XVIII'},
  {codigo:'R51',descripcion:'Cefalea',capitulo:'XVIII'},{codigo:'R52.9',descripcion:'Dolor no especificado',capitulo:'XVIII'},
  {codigo:'R53',descripcion:'Malestar y fatiga',capitulo:'XVIII'},{codigo:'R55',descripcion:'Síncope y colapso',capitulo:'XVIII'},
  {codigo:'R56.0',descripcion:'Convulsiones febriles',capitulo:'XVIII'},{codigo:'R56.8',descripcion:'Convulsiones no especificadas',capitulo:'XVIII'},
  {codigo:'R58',descripcion:'Hemorragia no clasificada',capitulo:'XVIII'},{codigo:'R59.0',descripcion:'Linfadenopatía localizada',capitulo:'XVIII'},
  {codigo:'R60.0',descripcion:'Edema localizado',capitulo:'XVIII'},{codigo:'R63.0',descripcion:'Anorexia',capitulo:'XVIII'},
  {codigo:'R63.4',descripcion:'Pérdida de peso anormal',capitulo:'XVIII'},{codigo:'R68.8',descripcion:'Otros síntomas generales',capitulo:'XVIII'},
  {codigo:'R73.9',descripcion:'Hiperglucemia no especificada',capitulo:'XVIII'},

  // ═══ Cap XIX: S00-T98 Traumatismos ═══
  {codigo:'S00.9',descripcion:'Traumatismo superficial de la cabeza',capitulo:'XIX'},{codigo:'S01.9',descripcion:'Herida de la cabeza',capitulo:'XIX'},
  {codigo:'S02.0',descripcion:'Fractura de bóveda craneal',capitulo:'XIX'},{codigo:'S02.4',descripcion:'Fractura del malar y maxilar',capitulo:'XIX'},
  {codigo:'S05.9',descripcion:'Traumatismo del ojo',capitulo:'XIX'},{codigo:'S06.0',descripcion:'Conmoción cerebral (TCE leve)',capitulo:'XIX'},
  {codigo:'S06.9',descripcion:'Traumatismo intracraneal no especificado',capitulo:'XIX'},{codigo:'S09.9',descripcion:'Traumatismo de cabeza no especificado',capitulo:'XIX'},
  {codigo:'S12.9',descripcion:'Fractura de vértebra cervical',capitulo:'XIX'},{codigo:'S13.4',descripcion:'Esguince cervical',capitulo:'XIX'},
  {codigo:'S22.3',descripcion:'Fractura costal',capitulo:'XIX'},{codigo:'S27.0',descripcion:'Neumotórax traumático',capitulo:'XIX'},
  {codigo:'S32.0',descripcion:'Fractura de vértebra lumbar',capitulo:'XIX'},{codigo:'S42.0',descripcion:'Fractura de clavícula',capitulo:'XIX'},
  {codigo:'S42.2',descripcion:'Fractura de húmero proximal',capitulo:'XIX'},{codigo:'S42.3',descripcion:'Fractura de diáfisis del húmero',capitulo:'XIX'},
  {codigo:'S52.5',descripcion:'Fractura de radio distal (Colles)',capitulo:'XIX'},{codigo:'S52.9',descripcion:'Fractura de antebrazo',capitulo:'XIX'},
  {codigo:'S62.0',descripcion:'Fractura de escafoides',capitulo:'XIX'},{codigo:'S62.6',descripcion:'Fractura de falange de mano',capitulo:'XIX'},
  {codigo:'S63.5',descripcion:'Esguince de muñeca',capitulo:'XIX'},{codigo:'S72.0',descripcion:'Fractura de cuello femoral',capitulo:'XIX'},
  {codigo:'S72.1',descripcion:'Fractura pertrocantérica de fémur',capitulo:'XIX'},{codigo:'S72.3',descripcion:'Fractura de diáfisis de fémur',capitulo:'XIX'},
  {codigo:'S76.1',descripcion:'Lesión del tendón cuádriceps',capitulo:'XIX'},{codigo:'S82.0',descripcion:'Fractura de rótula',capitulo:'XIX'},
  {codigo:'S82.5',descripcion:'Fractura de maléolo medial',capitulo:'XIX'},{codigo:'S82.6',descripcion:'Fractura de maléolo lateral',capitulo:'XIX'},
  {codigo:'S82.8',descripcion:'Fractura bimaleolar',capitulo:'XIX'},{codigo:'S83.5',descripcion:'Esguince de rodilla (LCA/LCL)',capitulo:'XIX'},
  {codigo:'S86.0',descripcion:'Lesión del tendón de Aquiles',capitulo:'XIX'},{codigo:'S92.0',descripcion:'Fractura de calcáneo',capitulo:'XIX'},
  {codigo:'S93.4',descripcion:'Esguince de tobillo',capitulo:'XIX'},{codigo:'T14.9',descripcion:'Traumatismo no especificado',capitulo:'XIX'},
  {codigo:'T15.9',descripcion:'Cuerpo extraño en ojo',capitulo:'XIX'},{codigo:'T17.9',descripcion:'Cuerpo extraño en vía respiratoria',capitulo:'XIX'},
  {codigo:'T18.9',descripcion:'Cuerpo extraño en aparato digestivo',capitulo:'XIX'},{codigo:'T30.0',descripcion:'Quemadura grado no especificado',capitulo:'XIX'},
  {codigo:'T63.4',descripcion:'Envenenamiento por arácnidos',capitulo:'XIX'},{codigo:'T65.9',descripcion:'Intoxicación por sustancias',capitulo:'XIX'},
  {codigo:'T75.1',descripcion:'Ahogamiento y sumersión',capitulo:'XIX'},{codigo:'T78.2',descripcion:'Choque anafiláctico',capitulo:'XIX'},
  {codigo:'T78.4',descripcion:'Alergia no especificada',capitulo:'XIX'},{codigo:'T79.3',descripcion:'Infección postraumática de herida',capitulo:'XIX'},
  {codigo:'T81.4',descripcion:'Infección posquirúrgica',capitulo:'XIX'},{codigo:'T88.7',descripcion:'Reacción adversa a medicamento',capitulo:'XIX'},

  // ═══ Cap XX: V01-Y98 Causas externas ═══
  {codigo:'V89.2',descripcion:'Accidente de tránsito',capitulo:'XX'},{codigo:'W01',descripcion:'Caída por tropiezo/resbalón',capitulo:'XX'},
  {codigo:'W06',descripcion:'Caída de la cama',capitulo:'XX'},{codigo:'W10',descripcion:'Caída en/de escaleras',capitulo:'XX'},
  {codigo:'W19',descripcion:'Caída no especificada',capitulo:'XX'},{codigo:'W54',descripcion:'Mordedura de perro',capitulo:'XX'},
  {codigo:'X00',descripcion:'Exposición al fuego',capitulo:'XX'},{codigo:'X30',descripcion:'Exposición a calor excesivo',capitulo:'XX'},
  {codigo:'X58',descripcion:'Exposición a otros factores',capitulo:'XX'},{codigo:'X85',descripcion:'Agresión con fármacos',capitulo:'XX'},
  {codigo:'Y04',descripcion:'Agresión con fuerza corporal',capitulo:'XX'},{codigo:'Y06',descripcion:'Negligencia y abandono',capitulo:'XX'},
  {codigo:'Y09',descripcion:'Agresión por medio no especificado',capitulo:'XX'},

  // ═══ Cap XXI: Z00-Z99 Factores que influyen en estado de salud ═══
  {codigo:'Z00.0',descripcion:'Examen médico general',capitulo:'XXI'},{codigo:'Z00.1',descripcion:'Control de salud del niño',capitulo:'XXI'},
  {codigo:'Z01.0',descripcion:'Examen de ojos y visión',capitulo:'XXI'},{codigo:'Z01.1',descripcion:'Examen de oídos y audición',capitulo:'XXI'},
  {codigo:'Z01.4',descripcion:'Examen ginecológico',capitulo:'XXI'},{codigo:'Z02.0',descripcion:'Examen para admisión educativa',capitulo:'XXI'},
  {codigo:'Z09.9',descripcion:'Seguimiento post-tratamiento',capitulo:'XXI'},{codigo:'Z12.1',descripcion:'Detección de neoplasia de intestino',capitulo:'XXI'},
  {codigo:'Z12.3',descripcion:'Detección de neoplasia de mama',capitulo:'XXI'},{codigo:'Z12.4',descripcion:'Detección de neoplasia de cuello uterino',capitulo:'XXI'},
  {codigo:'Z13.1',descripcion:'Detección de diabetes mellitus',capitulo:'XXI'},{codigo:'Z20.8',descripcion:'Contacto con enfermedad transmisible',capitulo:'XXI'},
  {codigo:'Z23',descripcion:'Necesidad de inmunización',capitulo:'XXI'},{codigo:'Z30.0',descripcion:'Consejo anticonceptivo general',capitulo:'XXI'},
  {codigo:'Z30.4',descripcion:'Vigilancia de anticonceptivos',capitulo:'XXI'},{codigo:'Z30.5',descripcion:'Vigilancia de DIU',capitulo:'XXI'},
  {codigo:'Z32.1',descripcion:'Embarazo confirmado',capitulo:'XXI'},{codigo:'Z34.0',descripcion:'Supervisión de primer embarazo normal',capitulo:'XXI'},
  {codigo:'Z34.9',descripcion:'Supervisión de embarazo normal',capitulo:'XXI'},{codigo:'Z36',descripcion:'Investigación prenatal',capitulo:'XXI'},
  {codigo:'Z38.0',descripcion:'Recién nacido único en hospital',capitulo:'XXI'},{codigo:'Z39.0',descripcion:'Atención postparto inmediata',capitulo:'XXI'},
  {codigo:'Z48.0',descripcion:'Atención de herida quirúrgica',capitulo:'XXI'},{codigo:'Z51.1',descripcion:'Sesión de quimioterapia',capitulo:'XXI'},
  {codigo:'Z51.0',descripcion:'Sesión de radioterapia',capitulo:'XXI'},{codigo:'Z53.9',descripcion:'Procedimiento no realizado',capitulo:'XXI'},
  {codigo:'Z71.1',descripcion:'Consulta por temor a enfermedad',capitulo:'XXI'},{codigo:'Z71.3',descripcion:'Consejo dietético y vigilancia',capitulo:'XXI'},
  {codigo:'Z73.0',descripcion:'Agotamiento (burnout)',capitulo:'XXI'},{codigo:'Z76.0',descripcion:'Expedición de receta repetida',capitulo:'XXI'},
  {codigo:'Z80.0',descripcion:'Antecedente familiar de neoplasia digestiva',capitulo:'XXI'},{codigo:'Z82.4',descripcion:'Antecedente familiar de cardiopatía isquémica',capitulo:'XXI'},
  {codigo:'Z83.3',descripcion:'Antecedente familiar de diabetes mellitus',capitulo:'XXI'},{codigo:'Z85.3',descripcion:'Antecedente personal de neoplasia de mama',capitulo:'XXI'},
  {codigo:'Z86.4',descripcion:'Antecedente personal de abuso de sustancias',capitulo:'XXI'},{codigo:'Z87.1',descripcion:'Antecedente personal de enfermedades digestivas',capitulo:'XXI'},
  {codigo:'Z88.0',descripcion:'Alergia a penicilina',capitulo:'XXI'},{codigo:'Z91.0',descripcion:'Antecedente de alergia no a fármacos',capitulo:'XXI'},
  {codigo:'Z96.1',descripcion:'Presencia de lente intraocular',capitulo:'XXI'},{codigo:'Z96.6',descripcion:'Presencia de implante ortopédico articular',capitulo:'XXI'},
  {codigo:'Z97.1',descripcion:'Presencia de lente de contacto',capitulo:'XXI'},{codigo:'Z99.2',descripcion:'Dependencia de diálisis renal',capitulo:'XXI'},
];

module.exports = { CATALOGO_CIE10 };